import type { Lesson } from "../types";
import { jp, p, r } from "./text";

export const unit11: Lesson = {
  id: "unit-11",
  unit: 11,
  title: "过去表达：でした・かったです",
  subtitle: "说明过去的人、事物、状态和感受",
  description:
    "学习名词句、な形容词句和い形容词句的过去表达，用简单句子说昨天、上周的情况。",
  duration: "约 50 分钟",
  accent: "#8a6fb8",
  goals: [
    "用「名词でした」表达过去的身份或情况",
    "用「ではありませんでした」表达过去否定",
    "掌握い形容词和な形容词的过去式",
  ],
  vocabulary: [
    {
      id: "u11-w1",
      japanese: jp(r("昨日", "きのう", "昨天")),
      kana: "きのう",
      meaning: "昨天",
      partOfSpeech: "名词",
      example: jp(r("昨日", "きのう", "昨天"), p("は"), r("雨", "あめ", "雨"), p("でした。")),
      exampleMeaning: "昨天是雨天。",
    },
    {
      id: "u11-w2",
      japanese: jp(r("先週", "せんしゅう", "上周")),
      kana: "せんしゅう",
      meaning: "上周",
      partOfSpeech: "名词",
      example: jp(r("先週", "せんしゅう", "上周"), p("は"), r("忙", "いそが", "忙"), p("しかったです。")),
      exampleMeaning: "上周很忙。",
    },
    {
      id: "u11-w3",
      japanese: jp(r("天気", "てんき", "天气")),
      kana: "てんき",
      meaning: "天气",
      partOfSpeech: "名词",
      example: jp(r("昨日", "きのう", "昨天"), p("の"), r("天気", "てんき", "天气"), p("はよかったです。")),
      exampleMeaning: "昨天的天气很好。",
    },
    {
      id: "u11-w4",
      japanese: jp(r("雨", "あめ", "雨")),
      kana: "あめ",
      meaning: "雨；雨天",
      partOfSpeech: "名词",
      example: jp(r("朝", "あさ", "早上"), p("は"), r("雨", "あめ", "雨"), p("でした。")),
      exampleMeaning: "早上是雨天。",
    },
    {
      id: "u11-w5",
      japanese: jp(r("試験", "しけん", "考试")),
      kana: "しけん",
      meaning: "考试",
      partOfSpeech: "名词",
      example: jp(r("試験", "しけん", "考试"), p("は"), r("難", "むずか", "难"), p("しかったです。")),
      exampleMeaning: "考试很难。",
    },
    {
      id: "u11-w6",
      japanese: jp(r("楽", "たの", "快乐"), p("しい")),
      kana: "たのしい",
      meaning: "开心的；有趣的",
      partOfSpeech: "い形容词",
      example: jp(r("旅行", "りょこう", "旅行"), p("は"), r("楽", "たの", "快乐"), p("しかったです。")),
      exampleMeaning: "旅行很开心。",
    },
    {
      id: "u11-w7",
      japanese: jp(r("忙", "いそが", "忙"), p("しい")),
      kana: "いそがしい",
      meaning: "忙的",
      partOfSpeech: "い形容词",
      example: jp(r("昨日", "きのう", "昨天"), p("は"), r("忙", "いそが", "忙"), p("しくありませんでした。")),
      exampleMeaning: "昨天不忙。",
    },
    {
      id: "u11-w8",
      japanese: jp(r("難", "むずか", "难"), p("しい")),
      kana: "むずかしい",
      meaning: "难的",
      partOfSpeech: "い形容词",
      example: jp(r("宿題", "しゅくだい", "作业"), p("は"), r("難", "むずか", "难"), p("しくありませんでした。")),
      exampleMeaning: "作业不难。",
    },
    {
      id: "u11-w9",
      japanese: jp(r("静", "しず", "安静"), p("か")),
      kana: "しずか",
      meaning: "安静的",
      partOfSpeech: "な形容词",
      example: jp(r("教室", "きょうしつ", "教室"), p("は"), r("静", "しず", "安静"), p("かでした。")),
      exampleMeaning: "教室很安静。",
    },
    {
      id: "u11-w10",
      japanese: "にぎやか",
      kana: "にぎやか",
      meaning: "热闹的",
      partOfSpeech: "な形容词",
      example: jp(r("駅", "えき", "车站"), p("はにぎやかでした。")),
      exampleMeaning: "车站很热闹。",
    },
    {
      id: "u11-w11",
      japanese: "ひま",
      kana: "ひま",
      meaning: "空闲的",
      partOfSpeech: "な形容词",
      example: jp(r("午後", "ごご", "下午"), p("はひまではありませんでした。")),
      exampleMeaning: "下午不空闲。",
    },
    {
      id: "u11-w12",
      japanese: jp(r("元気", "げんき", "精神好")),
      kana: "げんき",
      meaning: "有精神；健康",
      partOfSpeech: "な形容词",
      example: jp(r("昨日", "きのう", "昨天"), p("はあまり"), r("元気", "げんき", "精神好"), p("ではありませんでした。")),
      exampleMeaning: "昨天不太有精神。",
    },
  ],
  grammar: [
    {
      id: "u11-g1",
      title: "名词でした",
      structure: jp(r("昨日", "きのう", "昨天"), p("は"), r("休", "やす", "休息"), p("みでした")),
      explanation: "「名词 + でした」表示过去是某种身份、日期或情况。",
      usage: "用于礼貌地说明已经过去的事情。",
      examples: [
        { japanese: jp(r("昨日", "きのう", "昨天"), p("は"), r("雨", "あめ", "雨"), p("でした。")), meaning: "昨天是雨天。" },
        { japanese: jp(r("先週", "せんしゅう", "上周"), p("は"), r("試験", "しけん", "考试"), p("でした。")), meaning: "上周是考试。" },
      ],
    },
    {
      id: "u11-g2",
      title: "过去否定",
      structure: jp(r("雨", "あめ", "雨"), p("ではありませんでした")),
      explanation: "「名词 / な形容词 + ではありませんでした」表示过去不是某种情况。",
      usage: "口语中也常听到「じゃありませんでした」，这里先掌握正式形式。",
      examples: [
        { japanese: jp(r("昨日", "きのう", "昨天"), p("は"), r("雨", "あめ", "雨"), p("ではありませんでした。")), meaning: "昨天不是雨天。" },
        { japanese: jp(r("教室", "きょうしつ", "教室"), p("はにぎやかではありませんでした。")), meaning: "教室不热闹。" },
      ],
    },
    {
      id: "u11-g3",
      title: "い形容词过去式",
      structure: jp(r("楽", "たの", "快乐"), p("しい → "), r("楽", "たの", "快乐"), p("しかったです")),
      explanation: "い形容词去掉词尾「い」，加「かったです」表示过去肯定。",
      usage: "过去否定用「くありませんでした」。",
      examples: [
        { japanese: jp(r("旅行", "りょこう", "旅行"), p("は"), r("楽", "たの", "快乐"), p("しかったです。")), meaning: "旅行很开心。" },
        { japanese: jp(r("宿題", "しゅくだい", "作业"), p("は"), r("難", "むずか", "难"), p("しくありませんでした。")), meaning: "作业不难。" },
      ],
    },
    {
      id: "u11-g4",
      title: "な形容词过去式",
      structure: jp(r("静", "しず", "安静"), p("かでした / "), r("静", "しず", "安静"), p("かではありませんでした")),
      explanation: "な形容词的过去肯定接「でした」，过去否定接「ではありませんでした」。",
      usage: "「な」只在修饰名词时出现，句尾过去式不加「な」。",
      examples: [
        { japanese: jp(r("図書館", "としょかん", "图书馆"), p("は"), r("静", "しず", "安静"), p("かでした。")), meaning: "图书馆很安静。" },
        { japanese: jp(r("午後", "ごご", "下午"), p("はひまではありませんでした。")), meaning: "下午不空闲。" },
      ],
    },
  ],
  examples: [
    { japanese: jp(r("昨日", "きのう", "昨天"), p("は"), r("雨", "あめ", "雨"), p("でした。")), meaning: "昨天是雨天。" },
    { japanese: jp(r("先週", "せんしゅう", "上周"), p("は"), r("忙", "いそが", "忙"), p("しかったです。")), meaning: "上周很忙。" },
    { japanese: jp(r("試験", "しけん", "考试"), p("は"), r("難", "むずか", "难"), p("しくありませんでした。")), meaning: "考试不难。" },
    { japanese: jp(r("教室", "きょうしつ", "教室"), p("は"), r("静", "しず", "安静"), p("かでした。")), meaning: "教室很安静。" },
    { japanese: jp(r("駅", "えき", "车站"), p("はにぎやかでした。")), meaning: "车站很热闹。" },
    { japanese: jp(r("昨日", "きのう", "昨天"), p("は"), r("元気", "げんき", "精神好"), p("ではありませんでした。")), meaning: "昨天没有精神。" },
  ],
  reading: {
    title: "昨日の一日",
    intro: "两个同学课前聊昨天的情况。",
    lines: [
      {
        speaker: "陳",
        japanese: jp(r("昨日", "きのう", "昨天"), p("は"), r("忙", "いそが", "忙"), p("しかったですか。")),
        meaning: "昨天忙吗？",
        keywords: [{ term: "忙しかったです", reading: "いそがしかったです", meaning: "过去很忙" }],
      },
      {
        speaker: "林",
        japanese: jp(p("いいえ、あまり"), r("忙", "いそが", "忙"), p("しくありませんでした。")),
        meaning: "不，不太忙。",
        keywords: [{ term: "忙しくありませんでした", reading: "いそがしくありませんでした", meaning: "过去不忙" }],
      },
      {
        speaker: "陳",
        japanese: jp(r("天気", "てんき", "天气"), p("はどうでしたか。")),
        meaning: "天气怎么样？",
        keywords: [{ term: "どうでしたか", reading: "どうでしたか", meaning: "过去怎么样" }],
      },
      {
        speaker: "林",
        japanese: jp(r("朝", "あさ", "早上"), p("は"), r("雨", "あめ", "雨"), p("でした。でも、"), r("午後", "ごご", "下午"), p("はよかったです。")),
        meaning: "早上是雨天。不过下午很好。",
        keywords: [{ term: "雨でした", reading: "あめでした", meaning: "过去是雨天" }],
      },
      {
        speaker: "陳",
        japanese: jp(p("そうですか。"), r("図書館", "としょかん", "图书馆"), p("は"), r("静", "しず", "安静"), p("かでしたか。")),
        meaning: "这样啊。图书馆安静吗？",
        keywords: [{ term: "静かでした", reading: "しずかでした", meaning: "过去安静" }],
      },
      {
        speaker: "林",
        japanese: jp(p("はい、とても"), r("静", "しず", "安静"), p("かでした。")),
        meaning: "是的，非常安静。",
        keywords: [],
      },
    ],
  },
  exercises: [
    {
      id: "u11-e1",
      type: "multiple-choice",
      prompt: jp(r("昨日", "きのう", "昨天"), p("は"), r("雨", "あめ", "雨"), p("____。")),
      options: ["でした", "です", "ます", "ました"],
      correctAnswer: "でした",
      explanation: jp(r("雨", "あめ", "雨"), p("是名词，过去肯定用「でした」。")),
    },
    {
      id: "u11-e2",
      type: "fill-blank",
      prompt: jp(r("先週", "せんしゅう", "上周"), p("は"), r("試験", "しけん", "考试"), p(" ____。")),
      correctAnswer: "でした",
      explanation: jp(r("試験", "しけん", "考试"), p("是名词，过去肯定接「でした」。")),
    },
    {
      id: "u11-e3",
      type: "multiple-choice",
      prompt: jp(r("楽", "たの", "快乐"), p("しい 的过去肯定是哪一个？")),
      options: [jp(r("楽", "たの", "快乐"), p("しかったです")), jp(r("楽", "たの", "快乐"), p("しいでした")), jp(r("楽", "たの", "快乐"), p("しくでした")), jp(r("楽", "たの", "快乐"), p("しいませんでした"))],
      correctAnswer: jp(r("楽", "たの", "快乐"), p("しかったです")),
      explanation: jp(p("い形容词去掉「い」，加「かったです」。")),
    },
    {
      id: "u11-e4",
      type: "fill-blank",
      prompt: jp(r("試験", "しけん", "考试"), p("は"), r("難", "むずか", "难"), p("し____。")),
      correctAnswer: "かったです",
      explanation: jp(r("難", "むずか", "难"), p("しい → "), r("難", "むずか", "难"), p("しかったです。")),
    },
    {
      id: "u11-e5",
      type: "true-false",
      prompt: jp(p("判断用法。")),
      statement: jp(r("静", "しず", "安静"), p("か 的过去肯定可以说「"), r("静", "しず", "安静"), p("かでした」。")),
      correctAnswer: true,
      explanation: jp(r("静", "しず", "安静"), p("か 是な形容词，过去肯定接「でした」。")),
    },
    {
      id: "u11-e6",
      type: "order-sentence",
      prompt: jp(p("排列成“图书馆很安静”。")),
      parts: [r("図書館", "としょかん", "图书馆"), p("は"), r("静", "しず", "安静"), p("かでした")],
      correctOrder: [r("図書館", "としょかん", "图书馆"), p("は"), r("静", "しず", "安静"), p("かでした")],
      explanation: jp(p("な形容词过去句尾是「でした」。")),
    },
    {
      id: "u11-e7",
      type: "matching",
      prompt: jp(p("匹配现在式和过去式。")),
      pairs: [
        { left: jp(r("楽", "たの", "快乐"), p("しいです")), right: "楽しかったです" },
        { left: jp(r("忙", "いそが", "忙"), p("しいです")), right: "忙しかったです" },
        { left: jp(r("静", "しず", "安静"), p("かです")), right: "静かでした" },
        { left: jp(r("雨", "あめ", "雨"), p("です")), right: "雨でした" },
      ],
      explanation: jp(p("名词和な形容词接「でした」，い形容词变「かったです」。")),
    },
    {
      id: "u11-e8",
      type: "multiple-choice",
      prompt: jp(r("昨日", "きのう", "昨天"), p("は"), r("元気", "げんき", "精神好"), p("____。表示“昨天没有精神”。")),
      options: ["ではありませんでした", "でした", "くありませんでした", "ませんでした"],
      correctAnswer: "ではありませんでした",
      explanation: jp(r("元気", "げんき", "精神好"), p("是な形容词，过去否定用「ではありませんでした」。")),
    },
    {
      id: "u11-e9",
      type: "true-false",
      prompt: jp(p("判断句意。")),
      statement: jp(r("宿題", "しゅくだい", "作业"), p("は"), r("難", "むずか", "难"), p("しくありませんでした。表示“作业不难”。")),
      correctAnswer: true,
      explanation: jp(r("難", "むずか", "难"), p("しくありませんでした 是い形容词过去否定。")),
    },
    {
      id: "u11-e10",
      type: "order-sentence",
      prompt: jp(p("排列成“昨天不是雨天”。")),
      parts: [r("昨日", "きのう", "昨天"), p("は"), r("雨", "あめ", "雨"), p("ではありませんでした")],
      correctOrder: [r("昨日", "きのう", "昨天"), p("は"), r("雨", "あめ", "雨"), p("ではありませんでした")],
      explanation: jp(p("名词过去否定是「ではありませんでした」。")),
    },
    {
      id: "u11-e11",
      type: "fill-blank",
      prompt: jp(r("駅", "えき", "车站"), p("はにぎやか____。")),
      correctAnswer: "でした",
      explanation: jp(p("にぎやか 是な形容词，过去肯定接「でした」。")),
    },
    {
      id: "u11-e12",
      type: "multiple-choice",
      prompt: jp(p("哪一句表示“昨天不忙”？")),
      options: [
        jp(r("昨日", "きのう", "昨天"), p("は"), r("忙", "いそが", "忙"), p("しくありませんでした。")),
        jp(r("昨日", "きのう", "昨天"), p("は"), r("忙", "いそが", "忙"), p("しかったです。")),
        jp(r("昨日", "きのう", "昨天"), p("は"), r("忙", "いそが", "忙"), p("しいです。")),
        jp(r("昨日", "きのう", "昨天"), p("は"), r("忙", "いそが", "忙"), p("しいでした。")),
      ],
      correctAnswer: jp(r("昨日", "きのう", "昨天"), p("は"), r("忙", "いそが", "忙"), p("しくありませんでした。")),
      explanation: jp(r("忙", "いそが", "忙"), p("しい 的过去否定是「忙しくありませんでした」。")),
    },
  ],
};
