import type { Lesson } from "../types";
import { jp, p, r } from "./text";

export const unit13: Lesson = {
  id: "unit-13",
  unit: 13,
  title: "数字、价格与数量",
  subtitle: "说价格、几个、几本",
  description:
    "学习基础数字、日元价格和常见数量表达，用简单句子在店里询问和说明数量。",
  duration: "约 50 分钟",
  accent: "#b8845f",
  goals: [
    "用「円」说日元价格",
    "用「いくらですか」询问价格",
    "初步使用「一つ」「二つ」「一本」等数量表达",
  ],
  vocabulary: [
    {
      id: "u13-w1",
      japanese: jp(r("円", "えん", "日元")),
      kana: "えん",
      meaning: "日元",
      partOfSpeech: "量词",
      example: jp(p("このノートは"), r("百円", "ひゃくえん", "一百日元"), p("です。")),
      exampleMeaning: "这个笔记本是一百日元。",
    },
    {
      id: "u13-w2",
      japanese: "いくら",
      kana: "いくら",
      meaning: "多少钱",
      partOfSpeech: "疑问词",
      example: jp(p("これはいくらですか。")),
      exampleMeaning: "这个多少钱？",
    },
    {
      id: "u13-w3",
      japanese: jp(r("百円", "ひゃくえん", "一百日元")),
      kana: "ひゃくえん",
      meaning: "一百日元",
      partOfSpeech: "数量表达",
      example: jp(r("水", "みず", "水"), p("は"), r("百円", "ひゃくえん", "一百日元"), p("です。")),
      exampleMeaning: "水是一百日元。",
    },
    {
      id: "u13-w4",
      japanese: jp(r("三百円", "さんびゃくえん", "三百日元")),
      kana: "さんびゃくえん",
      meaning: "三百日元",
      partOfSpeech: "数量表达",
      example: jp(r("弁当", "べんとう", "便当"), p("は"), r("三百円", "さんびゃくえん", "三百日元"), p("です。")),
      exampleMeaning: "便当是三百日元。",
    },
    {
      id: "u13-w5",
      japanese: jp(r("千円", "せんえん", "一千日元")),
      kana: "せんえん",
      meaning: "一千日元",
      partOfSpeech: "数量表达",
      example: jp(p("この"), r("本", "ほん", "书"), p("は"), r("千円", "せんえん", "一千日元"), p("です。")),
      exampleMeaning: "这本书是一千日元。",
    },
    {
      id: "u13-w6",
      japanese: jp(r("一", "ひと", "一"), p("つ")),
      kana: "ひとつ",
      meaning: "一个",
      partOfSpeech: "数量表达",
      example: jp(p("おにぎりを"), r("一", "ひと", "一"), p("つください。")),
      exampleMeaning: "请给我一个饭团。",
    },
    {
      id: "u13-w7",
      japanese: jp(r("二", "ふた", "二"), p("つ")),
      kana: "ふたつ",
      meaning: "两个",
      partOfSpeech: "数量表达",
      example: jp(p("パンを"), r("二", "ふた", "二"), p("つ"), r("買", "か", "买"), p("いました。")),
      exampleMeaning: "买了两个面包。",
    },
    {
      id: "u13-w8",
      japanese: jp(r("三", "みっ", "三"), p("つ")),
      kana: "みっつ",
      meaning: "三个",
      partOfSpeech: "数量表达",
      example: jp(p("りんごを"), r("三", "みっ", "三"), p("つ"), r("食", "た", "吃"), p("べました。")),
      exampleMeaning: "吃了三个苹果。",
    },
    {
      id: "u13-w9",
      japanese: jp(r("何", "いく", "几"), p("つ")),
      kana: "いくつ",
      meaning: "几个",
      partOfSpeech: "疑问词",
      example: jp(p("りんごは"), r("何", "いく", "几"), p("つありますか。")),
      exampleMeaning: "苹果有几个？",
    },
    {
      id: "u13-w10",
      japanese: jp(r("一本", "いっぽん", "一根")),
      kana: "いっぽん",
      meaning: "一根；一瓶",
      partOfSpeech: "数量表达",
      example: jp(r("水", "みず", "水"), p("を"), r("一本", "いっぽん", "一瓶"), p("ください。")),
      exampleMeaning: "请给我一瓶水。",
    },
    {
      id: "u13-w11",
      japanese: jp(r("二本", "にほん", "两根")),
      kana: "にほん",
      meaning: "两根；两瓶",
      partOfSpeech: "数量表达",
      example: jp(r("鉛筆", "えんぴつ", "铅笔"), p("を"), r("二本", "にほん", "两根"), p(""), r("買", "か", "买"), p("いました。")),
      exampleMeaning: "买了两支铅笔。",
    },
    {
      id: "u13-w12",
      japanese: jp(r("店", "みせ", "店")),
      kana: "みせ",
      meaning: "店",
      partOfSpeech: "名词",
      example: jp(r("店", "みせ", "店"), p("でパンを"), r("二", "ふた", "二"), p("つ"), r("買", "か", "买"), p("いました。")),
      exampleMeaning: "在店里买了两个面包。",
    },
  ],
  grammar: [
    {
      id: "u13-g1",
      title: "价格表达",
      structure: jp(p("これは"), r("三百円", "さんびゃくえん", "三百日元"), p("です")),
      explanation: "价格直接放在「です」前面。日元用「円」。",
      usage: "询问价格时说「いくらですか」。",
      examples: [
        { japanese: jp(p("このノートは"), r("百円", "ひゃくえん", "一百日元"), p("です。")), meaning: "这个笔记本是一百日元。" },
        { japanese: jp(p("この"), r("本", "ほん", "书"), p("はいくらですか。")), meaning: "这本书多少钱？" },
      ],
    },
    {
      id: "u13-g2",
      title: "几个：つ",
      structure: jp(p("りんごを"), r("三", "みっ", "三"), p("つ"), r("食", "た", "吃"), p("べました")),
      explanation: "「一つ、二つ、三つ」可用于很多普通物品的数量。",
      usage: "先掌握一到三个，避免一次记太多特殊读法。",
      examples: [
        { japanese: jp(p("パンを"), r("二", "ふた", "二"), p("つ"), r("買", "か", "买"), p("いました。")), meaning: "买了两个面包。" },
        { japanese: jp(p("おにぎりを"), r("一", "ひと", "一"), p("つください。")), meaning: "请给我一个饭团。" },
      ],
    },
    {
      id: "u13-g3",
      title: "长条物：本",
      structure: jp(r("水", "みず", "水"), p("を"), r("一本", "いっぽん", "一瓶"), p("ください")),
      explanation: "细长物或瓶装饮料常用「本」来数。",
      usage: "「一本」「二本」读音不同，先作为固定表达记忆。",
      examples: [
        { japanese: jp(r("水", "みず", "水"), p("を"), r("一本", "いっぽん", "一瓶"), p("ください。")), meaning: "请给我一瓶水。" },
        { japanese: jp(r("鉛筆", "えんぴつ", "铅笔"), p("を"), r("二本", "にほん", "两根"), p(""), r("買", "か", "买"), p("いました。")), meaning: "买了两支铅笔。" },
      ],
    },
  ],
  examples: [
    { japanese: jp(p("これは"), r("三百円", "さんびゃくえん", "三百日元"), p("です。")), meaning: "这个是三百日元。" },
    { japanese: jp(p("この"), r("本", "ほん", "书"), p("はいくらですか。")), meaning: "这本书多少钱？" },
    { japanese: jp(p("パンを"), r("二", "ふた", "二"), p("つ"), r("買", "か", "买"), p("いました。")), meaning: "买了两个面包。" },
    { japanese: jp(r("水", "みず", "水"), p("を"), r("一本", "いっぽん", "一瓶"), p("ください。")), meaning: "请给我一瓶水。" },
    { japanese: jp(p("りんごは"), r("何", "いく", "几"), p("つありますか。")), meaning: "苹果有几个？" },
    { japanese: jp(r("店", "みせ", "店"), p("でおにぎりを"), r("一", "ひと", "一"), p("つ"), r("買", "か", "买"), p("いました。")), meaning: "在店里买了一个饭团。" },
  ],
  reading: {
    title: "小さな店で",
    intro: "在小店里买简单的东西。",
    lines: [
      {
        speaker: "客",
        japanese: jp(p("すみません。このパンはいくらですか。")),
        meaning: "不好意思，这个面包多少钱？",
        keywords: [{ term: "いくら", reading: "いくら", meaning: "多少钱" }],
      },
      {
        speaker: "店員",
        japanese: jp(r("一", "ひと", "一"), p("つ"), r("百円", "ひゃくえん", "一百日元"), p("です。")),
        meaning: "一个一百日元。",
        keywords: [{ term: "一つ", reading: "ひとつ", meaning: "一个" }],
      },
      {
        speaker: "客",
        japanese: jp(p("では、パンを"), r("二", "ふた", "二"), p("つと"), r("水", "みず", "水"), p("を"), r("一本", "いっぽん", "一瓶"), p("ください。")),
        meaning: "那么，请给我两个面包和一瓶水。",
        keywords: [{ term: "一本", reading: "いっぽん", meaning: "一瓶；一根" }],
      },
      {
        speaker: "店員",
        japanese: jp(p("はい。ぜんぶで"), r("三百円", "さんびゃくえん", "三百日元"), p("です。")),
        meaning: "好的。总共三百日元。",
        keywords: [{ term: "三百円", reading: "さんびゃくえん", meaning: "三百日元" }],
      },
      {
        speaker: "客",
        japanese: jp(p("はい、"), r("三百円", "さんびゃくえん", "三百日元"), p("です。")),
        meaning: "好的，三百日元。",
        keywords: [],
      },
    ],
  },
  exercises: [
    {
      id: "u13-e1",
      type: "multiple-choice",
      prompt: jp(p("「100円」的日语读法是哪一个？")),
      options: [jp(r("百円", "ひゃくえん", "一百日元")), jp(r("千円", "せんえん", "一千日元")), jp(r("三百円", "さんびゃくえん", "三百日元")), jp(r("円", "えん", "日元"))],
      correctAnswer: jp(r("百円", "ひゃくえん", "一百日元")),
      explanation: jp(r("百円", "ひゃくえん", "一百日元"), p("是一百日元。")),
    },
    {
      id: "u13-e2",
      type: "fill-blank",
      prompt: jp(p("これはいくら____。")),
      correctAnswer: "ですか",
      explanation: jp(p("询问价格常用「いくらですか」。")),
    },
    {
      id: "u13-e3",
      type: "order-sentence",
      prompt: jp(p("排列成“这个笔记本是一百日元”。")),
      parts: [p("このノートは"), r("百円", "ひゃくえん", "一百日元"), p("です")],
      correctOrder: [p("このノートは"), r("百円", "ひゃくえん", "一百日元"), p("です")],
      explanation: jp(p("物品 + は + 价格 + です。")),
    },
    {
      id: "u13-e4",
      type: "multiple-choice",
      prompt: jp(p("「两个」常用哪一个表达？")),
      options: [jp(r("二", "ふた", "二"), p("つ")), jp(r("一", "ひと", "一"), p("つ")), jp(r("三", "みっ", "三"), p("つ")), jp(r("一本", "いっぽん", "一瓶"))],
      correctAnswer: jp(r("二", "ふた", "二"), p("つ")),
      explanation: jp(r("二", "ふた", "二"), p("つ表示两个。")),
    },
    {
      id: "u13-e5",
      type: "true-false",
      prompt: jp(p("判断用法。")),
      statement: jp(r("水", "みず", "水"), p("を"), r("一本", "いっぽん", "一瓶"), p("ください。可以表示“请给我一瓶水”。")),
      correctAnswer: true,
      explanation: jp(r("一本", "いっぽん", "一瓶"), p("可用于瓶装饮料。")),
    },
    {
      id: "u13-e6",
      type: "matching",
      prompt: jp(p("匹配数量和意思。")),
      pairs: [
        { left: jp(r("一", "ひと", "一"), p("つ")), right: "一个" },
        { left: jp(r("二", "ふた", "二"), p("つ")), right: "两个" },
        { left: jp(r("三", "みっ", "三"), p("つ")), right: "三个" },
        { left: jp(r("一本", "いっぽん", "一瓶")), right: "一瓶；一根" },
      ],
      explanation: jp(p("这些都是基础数量表达。")),
    },
    {
      id: "u13-e7",
      type: "fill-blank",
      prompt: jp(p("パンを"), r("二", "ふた", "二"), p("つ"), r("買", "か", "买"), p("い____。")),
      correctAnswer: "ました",
      explanation: jp(r("買", "か", "买"), p("いました 表示买了。")),
    },
    {
      id: "u13-e8",
      type: "multiple-choice",
      prompt: jp(p("哪一句表示“苹果有几个？”")),
      options: [
        jp(p("りんごは"), r("何", "いく", "几"), p("つありますか。")),
        jp(p("りんごは"), r("一本", "いっぽん", "一瓶"), p("ありますか。")),
        jp(p("りんごを"), r("百円", "ひゃくえん", "一百日元"), p("ですか。")),
        jp(p("りんごへ"), r("何", "なに", "什么"), p("ですか。")),
      ],
      correctAnswer: jp(p("りんごは"), r("何", "いく", "几"), p("つありますか。")),
      explanation: jp(r("何", "いく", "几"), p("つ表示“几个”。")),
    },
    {
      id: "u13-e9",
      type: "order-sentence",
      prompt: jp(p("排列成“请给我一个饭团”。")),
      parts: [p("おにぎりを"), r("一", "ひと", "一"), p("つ"), p("ください")],
      correctOrder: [p("おにぎりを"), r("一", "ひと", "一"), p("つ"), p("ください")],
      explanation: jp(p("物品を + 数量 + ください。")),
    },
    {
      id: "u13-e10",
      type: "true-false",
      prompt: jp(p("判断句意。")),
      statement: jp(p("「"), r("千円", "せんえん", "一千日元"), p("です」表示“一千日元”。")),
      correctAnswer: true,
      explanation: jp(r("千円", "せんえん", "一千日元"), p("是一千日元。")),
    },
    {
      id: "u13-e11",
      type: "fill-blank",
      prompt: jp(r("水", "みず", "水"), p("を"), r("一", "いっ", "一"), p("____ください。")),
      correctAnswer: "ぽん",
      explanation: jp(r("一本", "いっぽん", "一瓶"), p("的读法是 いっぽん。")),
    },
    {
      id: "u13-e12",
      type: "multiple-choice",
      prompt: jp(p("哪一个通常用于数铅笔？")),
      options: [jp(r("二本", "にほん", "两根")), jp(r("二", "ふた", "二"), p("つ")), jp(r("三百円", "さんびゃくえん", "三百日元")), jp(r("何", "いく", "几"), p("つ"))],
      correctAnswer: jp(r("二本", "にほん", "两根")),
      explanation: jp(r("鉛筆", "えんぴつ", "铅笔"), p("这类细长物可用「本」。")),
    },
  ],
};
