import type { Lesson } from "../types";

export const unit3: Lesson = {
  id: "unit-3",
  unit: 3,
  title: "ここ・そこ・あそこ",
  subtitle: "问路与说明场所",
  description:
    "把指示词从物品扩展到地点，学习礼貌地询问位置，并说明人或设施在哪里。",
  duration: "约 40 分钟",
  accent: "#6779a8",
  goals: [
    "根据距离使用「ここ・そこ・あそこ」",
    "用「どこですか」询问地点",
    "用「〜にあります／います」说明存在位置",
  ],
  vocabulary: [
    {
      id: "u3-w1",
      japanese: "駅",
      kana: "えき",
      meaning: "车站",
      partOfSpeech: "名词",
      example: "駅はこの道の先です。",
      exampleMeaning: "车站在这条路前面。",
    },
    {
      id: "u3-w2",
      japanese: "図書館",
      kana: "としょかん",
      meaning: "图书馆",
      partOfSpeech: "名词",
      example: "図書館は六時までです。",
      exampleMeaning: "图书馆开放到六点。",
    },
    {
      id: "u3-w3",
      japanese: "受付",
      kana: "うけつけ",
      meaning: "接待处；前台",
      partOfSpeech: "名词",
      example: "受付は一階にあります。",
      exampleMeaning: "接待处在一楼。",
    },
    {
      id: "u3-w4",
      japanese: "教室",
      kana: "きょうしつ",
      meaning: "教室",
      partOfSpeech: "名词",
      example: "日本語の教室は三階です。",
      exampleMeaning: "日语教室在三楼。",
    },
    {
      id: "u3-w5",
      japanese: "食堂",
      kana: "しょくどう",
      meaning: "食堂",
      partOfSpeech: "名词",
      example: "昼は食堂が混みます。",
      exampleMeaning: "中午食堂很拥挤。",
    },
    {
      id: "u3-w6",
      japanese: "入口",
      kana: "いりぐち",
      meaning: "入口",
      partOfSpeech: "名词",
      example: "入口はあそこです。",
      exampleMeaning: "入口在那里。",
    },
    {
      id: "u3-w7",
      japanese: "隣",
      kana: "となり",
      meaning: "旁边；隔壁",
      partOfSpeech: "名词",
      example: "銀行は郵便局の隣です。",
      exampleMeaning: "银行在邮局旁边。",
    },
    {
      id: "u3-w8",
      japanese: "前",
      kana: "まえ",
      meaning: "前面",
      partOfSpeech: "名词",
      example: "駅の前にカフェがあります。",
      exampleMeaning: "车站前有一家咖啡店。",
    },
    {
      id: "u3-w9",
      japanese: "中",
      kana: "なか",
      meaning: "里面",
      partOfSpeech: "名词",
      example: "鞄の中に鍵があります。",
      exampleMeaning: "包里有钥匙。",
    },
    {
      id: "u3-w10",
      japanese: "店員",
      kana: "てんいん",
      meaning: "店员",
      partOfSpeech: "名词",
      example: "店員はレジの近くにいます。",
      exampleMeaning: "店员在收银台附近。",
    },
  ],
  grammar: [
    {
      id: "u3-g1",
      title: "指示地点",
      structure: "ここ / そこ / あそこ",
      explanation:
        "「ここ」指说话人附近，「そこ」指听话人附近，「あそこ」指离双方都较远的地点。",
      usage:
        "它们可直接作地点名词使用。更礼貌的对应表达是「こちら・そちら・あちら」。",
      examples: [
        { japanese: "ここは休憩室です。", meaning: "这里是休息室。" },
        { japanese: "そこは出口です。", meaning: "那里是出口。" },
        { japanese: "あそこは図書館です。", meaning: "那边是图书馆。" },
      ],
    },
    {
      id: "u3-g2",
      title: "询问地点",
      structure: "〜はどこですか",
      explanation:
        "「どこ」是地点疑问词，用来询问人、物或设施在哪里。",
      usage:
        "礼貌场合也可说「〜はどちらですか」。回答可用地点指示词或具体位置。",
      examples: [
        { japanese: "受付はどこですか。", meaning: "接待处在哪里？" },
        { japanese: "あそこです。", meaning: "在那边。" },
        { japanese: "教室は三階です。", meaning: "教室在三楼。" },
      ],
    },
    {
      id: "u3-g3",
      title: "事物的存在",
      structure: "地点 に 物 があります",
      explanation:
        "「あります」用于没有自主活动能力的事物，表示某处有某物。「に」标记存在的地点。",
      usage:
        "也可以把事物作为主题，说「物は地点にあります」。",
      examples: [
        { japanese: "一階に受付があります。", meaning: "一楼有接待处。" },
        { japanese: "鍵は机の上にあります。", meaning: "钥匙在桌上。" },
      ],
    },
    {
      id: "u3-g4",
      title: "人和动物的存在",
      structure: "地点 に 人・动物 がいます",
      explanation:
        "「います」用于人和动物。基本结构与「あります」相同。",
      usage:
        "询问人在何处时，可用「〜さんはどこにいますか」。",
      examples: [
        { japanese: "教室に先生がいます。", meaning: "教室里有老师。" },
        { japanese: "猫は庭にいます。", meaning: "猫在院子里。" },
      ],
    },
  ],
  examples: [
    { japanese: "ここは大学の図書館です。", meaning: "这里是大学图书馆。" },
    { japanese: "食堂はどこですか。", meaning: "食堂在哪里？" },
    { japanese: "入口はあそこです。", meaning: "入口在那边。" },
    { japanese: "一階に受付があります。", meaning: "一楼有接待处。" },
    { japanese: "先生は教室にいます。", meaning: "老师在教室里。" },
    { japanese: "駅の前に小さい書店があります。", meaning: "车站前有一家小书店。" },
  ],
  reading: {
    title: "市民センターで",
    intro: "第一次到市民活动中心，访客向前台询问教室的位置。",
    lines: [
      {
        speaker: "訪問者",
        japanese: "すみません。日本語の教室はどこですか。",
        meaning: "劳驾，请问日语教室在哪里？",
        keywords: [{ term: "どこ", reading: "どこ", meaning: "哪里" }],
      },
      {
        speaker: "受付",
        japanese: "二階にあります。階段はあそこです。",
        meaning: "在二楼。楼梯在那边。",
        keywords: [
          { term: "二階", reading: "にかい", meaning: "二楼" },
          { term: "階段", reading: "かいだん", meaning: "楼梯" },
        ],
      },
      {
        speaker: "訪問者",
        japanese: "エレベーターもありますか。",
        meaning: "也有电梯吗？",
        keywords: [{ term: "エレベーター", reading: "えれべーたー", meaning: "电梯" }],
      },
      {
        speaker: "受付",
        japanese: "はい。エレベーターは受付の隣にあります。",
        meaning: "有。电梯就在前台旁边。",
        keywords: [{ term: "隣", reading: "となり", meaning: "旁边" }],
      },
      {
        speaker: "訪問者",
        japanese: "ありがとうございます。先生はもう教室にいますか。",
        meaning: "谢谢。老师已经在教室了吗？",
        keywords: [{ term: "もう", reading: "もう", meaning: "已经" }],
      },
      {
        speaker: "受付",
        japanese: "はい、教室にいます。",
        meaning: "是的，老师在教室里。",
        keywords: [],
      },
    ],
  },
  exercises: [
    {
      id: "u3-e1",
      type: "multiple-choice",
      prompt: "询问“图书馆在哪里”，哪一句正确？",
      options: ["図書館はどこですか。", "図書館は何ですか。", "どこは図書館です。", "図書館の誰ですか。"],
      correctAnswer: "図書館はどこですか。",
      explanation: "地点疑问词「どこ」放在判断部分，构成「〜はどこですか」。",
    },
    {
      id: "u3-e2",
      type: "fill-blank",
      prompt: "补全句子：受付は ____ です。（指说话人所在的位置）",
      correctAnswer: "ここ",
      explanation: "说话人所在或附近的位置用「ここ」。",
    },
    {
      id: "u3-e3",
      type: "matching",
      prompt: "匹配设施与中文意思。",
      pairs: [
        { left: "受付", right: "接待处" },
        { left: "食堂", right: "食堂" },
        { left: "入口", right: "入口" },
        { left: "図書館", right: "图书馆" },
      ],
      explanation: "这些都是问路场景中的常用设施名称。",
    },
    {
      id: "u3-e4",
      type: "true-false",
      prompt: "判断存在动词的用法。",
      statement: "说明“教室里有老师”时，可以使用「あります」。",
      correctAnswer: false,
      explanation: "老师是人，应使用「います」：教室に先生がいます。",
    },
    {
      id: "u3-e5",
      type: "order-sentence",
      prompt: "排列成“车站前有咖啡店”。",
      parts: ["あります", "駅の前", "カフェ", "に", "が"],
      correctOrder: ["駅の前", "に", "カフェ", "が", "あります"],
      explanation: "存在句的基本顺序是「地点に + 事物が + あります」。",
    },
    {
      id: "u3-e6",
      type: "multiple-choice",
      prompt: "离说话人和听话人都较远的入口，应说什么？",
      options: ["入口はここです。", "入口はそこです。", "入口はあそこです。", "入口はどこです。"],
      correctAnswer: "入口はあそこです。",
      explanation: "离双方都较远的地点使用「あそこ」。",
    },
    {
      id: "u3-e7",
      type: "fill-blank",
      prompt: "选择存在动词：机の上に本が ____。",
      correctAnswer: "あります",
      explanation: "书是事物，表示其存在时使用「あります」。",
    },
    {
      id: "u3-e8",
      type: "fill-blank",
      prompt: "选择存在动词：庭に猫が ____。",
      correctAnswer: "います",
      explanation: "猫是动物，表示其存在时使用「います」。",
    },
    {
      id: "u3-e9",
      type: "true-false",
      prompt: "判断助词。",
      statement: "在「一階に受付があります」中，「に」标记存在地点。",
      correctAnswer: true,
      explanation: "「に」指出接待处存在的位置是一楼。",
    },
    {
      id: "u3-e10",
      type: "order-sentence",
      prompt: "排列成“老师在教室里”。",
      parts: ["先生", "教室", "います", "は", "に"],
      correctOrder: ["先生", "は", "教室", "に", "います"],
      explanation: "以人为主题时，可用「人は + 地点に + います」。",
    },
  ],
};
