import type { Lesson } from "../types";
import { jp, p, r } from "./text";

export const unit9: Lesson = {
  id: "unit-9",
  unit: 9,
  title: "あります / います",
  subtitle: "说明某处有什么、谁在哪里",
  description:
    "系统整理「あります」和「います」的区别，学习用地点に名词があります / います 表达存在。",
  duration: "约 45 分钟",
  accent: "#5f8ea2",
  goals: [
    "区分无生命物体和有生命的人、动物",
    "用「地点に物があります」说明某处有物",
    "用「地点に人・动物がいます」说明某处有人或动物",
  ],
  vocabulary: [
    {
      id: "u9-w1",
      japanese: "あります",
      kana: "あります",
      meaning: "有；在（物）",
      partOfSpeech: "动词",
      example: jp(r("机", "つくえ", "桌子"), p("の"), r("上", "うえ", "上面"), p("に"), r("本", "ほん", "书"), p("があります。")),
      exampleMeaning: "桌上有书。",
    },
    {
      id: "u9-w2",
      japanese: "います",
      kana: "います",
      meaning: "有；在（人、动物）",
      partOfSpeech: "动词",
      example: jp(r("教室", "きょうしつ", "教室"), p("に"), r("先生", "せんせい", "老师"), p("がいます。")),
      exampleMeaning: "教室里有老师。",
    },
    {
      id: "u9-w3",
      japanese: jp(r("机", "つくえ", "桌子")),
      kana: "つくえ",
      meaning: "桌子",
      partOfSpeech: "名词",
      example: jp(r("机", "つくえ", "桌子"), p("の"), r("下", "した", "下面"), p("に"), r("鞄", "かばん", "包"), p("があります。")),
      exampleMeaning: "桌下有包。",
    },
    {
      id: "u9-w4",
      japanese: jp(r("椅子", "いす", "椅子")),
      kana: "いす",
      meaning: "椅子",
      partOfSpeech: "名词",
      example: jp(r("部屋", "へや", "房间"), p("に"), r("椅子", "いす", "椅子"), p("があります。")),
      exampleMeaning: "房间里有椅子。",
    },
    {
      id: "u9-w5",
      japanese: jp(r("部屋", "へや", "房间")),
      kana: "へや",
      meaning: "房间",
      partOfSpeech: "名词",
      example: jp(r("部屋", "へや", "房间"), p("に"), r("窓", "まど", "窗户"), p("があります。")),
      exampleMeaning: "房间里有窗户。",
    },
    {
      id: "u9-w6",
      japanese: jp(r("庭", "にわ", "院子")),
      kana: "にわ",
      meaning: "院子",
      partOfSpeech: "名词",
      example: jp(r("庭", "にわ", "院子"), p("に"), r("猫", "ねこ", "猫"), p("がいます。")),
      exampleMeaning: "院子里有猫。",
    },
    {
      id: "u9-w7",
      japanese: jp(r("猫", "ねこ", "猫")),
      kana: "ねこ",
      meaning: "猫",
      partOfSpeech: "名词",
      example: jp(r("猫", "ねこ", "猫"), p("は"), r("椅子", "いす", "椅子"), p("の"), r("上", "うえ", "上面"), p("にいます。")),
      exampleMeaning: "猫在椅子上。",
    },
    {
      id: "u9-w8",
      japanese: jp(r("犬", "いぬ", "狗")),
      kana: "いぬ",
      meaning: "狗",
      partOfSpeech: "名词",
      example: jp(r("公園", "こうえん", "公园"), p("に"), r("犬", "いぬ", "狗"), p("がいます。")),
      exampleMeaning: "公园里有狗。",
    },
    {
      id: "u9-w9",
      japanese: jp(r("人", "ひと", "人")),
      kana: "ひと",
      meaning: "人",
      partOfSpeech: "名词",
      example: jp(r("駅", "えき", "车站"), p("に"), r("人", "ひと", "人"), p("がたくさんいます。")),
      exampleMeaning: "车站有很多人。",
    },
    {
      id: "u9-w10",
      japanese: jp(r("箱", "はこ", "盒子")),
      kana: "はこ",
      meaning: "盒子",
      partOfSpeech: "名词",
      example: jp(r("箱", "はこ", "盒子"), p("の"), r("中", "なか", "里面"), p("に"), r("写真", "しゃしん", "照片"), p("があります。")),
      exampleMeaning: "盒子里有照片。",
    },
    {
      id: "u9-w11",
      japanese: jp(r("窓", "まど", "窗户")),
      kana: "まど",
      meaning: "窗户",
      partOfSpeech: "名词",
      example: jp(r("窓", "まど", "窗户"), p("の"), r("近く", "ちかく", "附近"), p("に"), r("花", "はな", "花"), p("があります。")),
      exampleMeaning: "窗户附近有花。",
    },
    {
      id: "u9-w12",
      japanese: jp(r("男の人", "おとこのひと", "男人")),
      kana: "おとこのひと",
      meaning: "男士",
      partOfSpeech: "名词",
      example: jp(r("入口", "いりぐち", "入口"), p("に"), r("男の人", "おとこのひと", "男士"), p("がいます。")),
      exampleMeaning: "入口处有一位男士。",
    },
  ],
  grammar: [
    {
      id: "u9-g1",
      title: "物体用あります",
      structure: jp(r("場所", "ばしょ", "地点"), p("に "), r("物", "もの", "物品"), p("があります")),
      explanation: "没有自主活动能力的物品，用「あります」表示存在。",
      usage: "地点后接「に」，存在的物品后接「が」。",
      examples: [
        { japanese: jp(r("机", "つくえ", "桌子"), p("の"), r("上", "うえ", "上面"), p("に"), r("本", "ほん", "书"), p("があります。")), meaning: "桌上有书。" },
        { japanese: jp(r("部屋", "へや", "房间"), p("に"), r("窓", "まど", "窗户"), p("があります。")), meaning: "房间里有窗户。" },
      ],
    },
    {
      id: "u9-g2",
      title: "人和动物用います",
      structure: jp(r("場所", "ばしょ", "地点"), p("に "), r("人", "ひと", "人"), p("・"), r("動物", "どうぶつ", "动物"), p("がいます")),
      explanation: "人和动物用「います」表示存在。",
      usage: "猫、狗等动物也用「います」。",
      examples: [
        { japanese: jp(r("庭", "にわ", "院子"), p("に"), r("猫", "ねこ", "猫"), p("がいます。")), meaning: "院子里有猫。" },
        { japanese: jp(r("教室", "きょうしつ", "教室"), p("に"), r("先生", "せんせい", "老师"), p("がいます。")), meaning: "教室里有老师。" },
      ],
    },
    {
      id: "u9-g3",
      title: "以存在物为主题",
      structure: jp(r("名詞", "めいし", "名词"), p("は "), r("場所", "ばしょ", "地点"), p("にあります / います")),
      explanation: "已经知道谈论对象时，可把名词放在句首作主题。",
      usage: "物用「あります」，人和动物用「います」。",
      examples: [
        { japanese: jp(r("猫", "ねこ", "猫"), p("は"), r("椅子", "いす", "椅子"), p("の"), r("上", "うえ", "上面"), p("にいます。")), meaning: "猫在椅子上。" },
        { japanese: jp(r("写真", "しゃしん", "照片"), p("は"), r("箱", "はこ", "盒子"), p("の"), r("中", "なか", "里面"), p("にあります。")), meaning: "照片在盒子里。" },
      ],
    },
  ],
  examples: [
    { japanese: jp(r("机", "つくえ", "桌子"), p("の"), r("上", "うえ", "上面"), p("に"), r("本", "ほん", "书"), p("があります。")), meaning: "桌上有书。" },
    { japanese: jp(r("部屋", "へや", "房间"), p("に"), r("窓", "まど", "窗户"), p("があります。")), meaning: "房间里有窗户。" },
    { japanese: jp(r("庭", "にわ", "院子"), p("に"), r("猫", "ねこ", "猫"), p("がいます。")), meaning: "院子里有猫。" },
    { japanese: jp(r("教室", "きょうしつ", "教室"), p("に"), r("先生", "せんせい", "老师"), p("がいます。")), meaning: "教室里有老师。" },
    { japanese: jp(r("写真", "しゃしん", "照片"), p("は"), r("箱", "はこ", "盒子"), p("の"), r("中", "なか", "里面"), p("にあります。")), meaning: "照片在盒子里。" },
    { japanese: jp(r("駅", "えき", "车站"), p("に"), r("人", "ひと", "人"), p("がたくさんいます。")), meaning: "车站有很多人。" },
  ],
  reading: {
    title: "找东西",
    intro: "同学在教室里找自己的物品，也注意到房间里的东西。",
    lines: [
      {
        speaker: "陳",
        japanese: jp(r("私", "わたし", "我"), p("の"), r("鞄", "かばん", "包"), p("はどこにありますか。")),
        meaning: "我的包在哪里？",
        keywords: [{ term: "あります", reading: "あります", meaning: "有；在（物）" }],
      },
      {
        speaker: "葵",
        japanese: jp(r("机", "つくえ", "桌子"), p("の"), r("下", "した", "下面"), p("にありますよ。")),
        meaning: "在桌子下面哦。",
        keywords: [{ term: "下", reading: "した", meaning: "下面" }],
      },
      {
        speaker: "陳",
        japanese: jp(p("ありがとうございます。あ、"), r("窓", "まど", "窗户"), p("の"), r("近く", "ちかく", "附近"), p("に"), r("花", "はな", "花"), p("がありますね。")),
        meaning: "谢谢。啊，窗户附近有花呢。",
        keywords: [{ term: "花", reading: "はな", meaning: "花" }],
      },
      {
        speaker: "葵",
        japanese: jp(p("はい。"), r("先生", "せんせい", "老师"), p("の"), r("机", "つくえ", "桌子"), p("の"), r("上", "うえ", "上面"), p("にも"), r("写真", "しゃしん", "照片"), p("があります。")),
        meaning: "是的。老师的桌上也有照片。",
        keywords: [{ term: "写真", reading: "しゃしん", meaning: "照片" }],
      },
      {
        speaker: "陳",
        japanese: jp(r("教室", "きょうしつ", "教室"), p("に"), r("先生", "せんせい", "老师"), p("はいますか。")),
        meaning: "老师在教室里吗？",
        keywords: [{ term: "います", reading: "います", meaning: "有；在（人、动物）" }],
      },
      {
        speaker: "葵",
        japanese: jp(p("いいえ、"), r("先生", "せんせい", "老师"), p("はまだいません。")),
        meaning: "不，老师还不在。",
        keywords: [{ term: "まだ", reading: "まだ", meaning: "还；尚未" }],
      },
    ],
  },
  exercises: [
    {
      id: "u9-e1",
      type: "multiple-choice",
      prompt: jp(r("机", "つくえ", "桌子"), p("の"), r("上", "うえ", "上面"), p("に"), r("本", "ほん", "书"), p("が ____。")),
      options: ["あります", "います", "食べます", "好きです"],
      correctAnswer: "あります",
      explanation: jp(r("本", "ほん", "书"), p("是物品，用「あります」。")),
    },
    {
      id: "u9-e2",
      type: "fill-blank",
      prompt: jp(r("庭", "にわ", "院子"), p("に"), r("猫", "ねこ", "猫"), p("が ____。")),
      correctAnswer: "います",
      explanation: jp(r("猫", "ねこ", "猫"), p("是动物，用「います」。")),
    },
    {
      id: "u9-e3",
      type: "order-sentence",
      prompt: jp(p("排列成“房间里有窗户”。")),
      parts: [r("部屋", "へや", "房间"), r("窓", "まど", "窗户"), p("に"), p("があります"), p("が")],
      correctOrder: [r("部屋", "へや", "房间"), p("に"), r("窓", "まど", "窗户"), p("が"), p("あります")],
      explanation: jp(p("结构是「地点に + 物が + あります」。")),
    },
    {
      id: "u9-e4",
      type: "true-false",
      prompt: jp(p("判断用法。")),
      statement: jp(r("先生", "せんせい", "老师"), p("是人，所以用「います」。")),
      correctAnswer: true,
      explanation: jp(p("人和动物用「います」。")),
    },
    {
      id: "u9-e5",
      type: "matching",
      prompt: jp(p("匹配名词和存在动词。")),
      pairs: [
        { left: jp(r("本", "ほん", "书")), right: "物：あります" },
        { left: jp(r("猫", "ねこ", "猫")), right: "动物：います" },
        { left: jp(r("写真", "しゃしん", "照片")), right: "照片：あります" },
        { left: jp(r("男の人", "おとこのひと", "男士")), right: "人：います" },
      ],
      explanation: jp(p("物品用あります，人和动物用います。")),
    },
    {
      id: "u9-e6",
      type: "multiple-choice",
      prompt: jp(p("哪一句表示“照片在盒子里”？")),
      options: [
        jp(r("写真", "しゃしん", "照片"), p("は"), r("箱", "はこ", "盒子"), p("の"), r("中", "なか", "里面"), p("にあります。")),
        jp(r("写真", "しゃしん", "照片"), p("は"), r("箱", "はこ", "盒子"), p("の"), r("中", "なか", "里面"), p("にいます。")),
        jp(r("箱", "はこ", "盒子"), p("は"), r("写真", "しゃしん", "照片"), p("にあります。")),
        jp(r("写真", "しゃしん", "照片"), p("を"), r("箱", "はこ", "盒子"), p("にあります。")),
      ],
      correctAnswer: jp(r("写真", "しゃしん", "照片"), p("は"), r("箱", "はこ", "盒子"), p("の"), r("中", "なか", "里面"), p("にあります。")),
      explanation: jp(r("写真", "しゃしん", "照片"), p("是物品，用「あります」。")),
    },
    {
      id: "u9-e7",
      type: "fill-blank",
      prompt: jp(r("公園", "こうえん", "公园"), p("に"), r("犬", "いぬ", "狗"), p("が ____。")),
      correctAnswer: "います",
      explanation: jp(r("犬", "いぬ", "狗"), p("是动物，用「います」。")),
    },
    {
      id: "u9-e8",
      type: "true-false",
      prompt: jp(p("判断句意。")),
      statement: jp(r("駅", "えき", "车站"), p("に"), r("人", "ひと", "人"), p("がたくさんいます。表示“车站有很多人”。")),
      correctAnswer: true,
      explanation: jp(r("人", "ひと", "人"), p("用「います」，たくさん表示“很多”。")),
    },
    {
      id: "u9-e9",
      type: "order-sentence",
      prompt: jp(p("排列成“猫在椅子上”。")),
      parts: [r("猫", "ねこ", "猫"), p("は"), r("椅子", "いす", "椅子"), p("の"), r("上", "うえ", "上面"), p("に"), p("います")],
      correctOrder: [r("猫", "ねこ", "猫"), p("は"), r("椅子", "いす", "椅子"), p("の"), r("上", "うえ", "上面"), p("に"), p("います")],
      explanation: jp(r("猫", "ねこ", "猫"), p("是动物，作主题时句尾用「います」。")),
    },
    {
      id: "u9-e10",
      type: "multiple-choice",
      prompt: jp(r("入口", "いりぐち", "入口"), p("に"), r("男の人", "おとこのひと", "男人"), p("が ____。")),
      options: ["います", "あります", "読みます", "高いです"],
      correctAnswer: "います",
      explanation: jp(r("男の人", "おとこのひと", "男人"), p("是人，用「います」。")),
    },
  ],
};
