import type { Lesson } from "../types";
import { jp, p, r } from "./text";

export const unit6: Lesson = {
  id: "unit-6",
  unit: 6,
  title: "助词 を / で / に 的基础用法",
  subtitle: "把动作、地点和时间连接起来",
  description:
    "学习用「を」标记动作对象，用「で」标记动作场所，用「に」标记时间点和目的地。",
  duration: "约 45 分钟",
  accent: "#7e9a68",
  goals: [
    "区分「を」「で」「に」的基础功能",
    "用「地点で动作」说明在哪里做某事",
    "用「时间に」和「地点に」说明时间点与目的地",
  ],
  vocabulary: [
    {
      id: "u6-w1",
      japanese: jp(r("教室", "きょうしつ", "教室")),
      kana: "きょうしつ",
      meaning: "教室",
      partOfSpeech: "名词",
      example: jp(r("教室", "きょうしつ", "教室"), p("で"), r("日本語", "にほんご", "日语"), p("を"), r("勉強", "べんきょう", "学习"), p("します。")),
      exampleMeaning: "在教室学习日语。",
    },
    {
      id: "u6-w2",
      japanese: jp(r("家", "いえ", "家")),
      kana: "いえ",
      meaning: "家",
      partOfSpeech: "名词",
      example: jp(r("家", "いえ", "家"), p("で"), r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。")),
      exampleMeaning: "在家读书。",
    },
    {
      id: "u6-w3",
      japanese: jp(r("駅", "えき", "车站")),
      kana: "えき",
      meaning: "车站",
      partOfSpeech: "名词",
      example: jp(r("駅", "えき", "车站"), p("に"), r("行きます", "いきます", "去"), p("。")),
      exampleMeaning: "去车站。",
    },
    {
      id: "u6-w4",
      japanese: jp(r("公園", "こうえん", "公园")),
      kana: "こうえん",
      meaning: "公园",
      partOfSpeech: "名词",
      example: jp(r("公園", "こうえん", "公园"), p("で"), r("友達", "ともだち", "朋友"), p("と"), r("話します", "はなします", "说话"), p("。")),
      exampleMeaning: "在公园和朋友说话。",
    },
    {
      id: "u6-w5",
      japanese: jp(r("店", "みせ", "商店")),
      kana: "みせ",
      meaning: "店",
      partOfSpeech: "名词",
      example: jp(r("店", "みせ", "商店"), p("でパンを"), r("買います", "かいます", "买"), p("。")),
      exampleMeaning: "在店里买面包。",
    },
    {
      id: "u6-w6",
      japanese: jp(r("七時", "しちじ", "七点")),
      kana: "しちじ",
      meaning: "七点",
      partOfSpeech: "时间词",
      example: jp(r("七時", "しちじ", "七点"), p("に"), r("起きます", "おきます", "起床"), p("。")),
      exampleMeaning: "七点起床。",
    },
    {
      id: "u6-w7",
      japanese: jp(r("朝ご飯", "あさごはん", "早饭")),
      kana: "あさごはん",
      meaning: "早饭",
      partOfSpeech: "名词",
      example: jp(r("朝ご飯", "あさごはん", "早饭"), p("を"), r("食べます", "たべます", "吃"), p("。")),
      exampleMeaning: "吃早饭。",
    },
    {
      id: "u6-w8",
      japanese: jp(r("手紙", "てがみ", "信")),
      kana: "てがみ",
      meaning: "信",
      partOfSpeech: "名词",
      example: jp(r("手紙", "てがみ", "信"), p("を"), r("書きます", "かきます", "写"), p("。")),
      exampleMeaning: "写信。",
    },
    {
      id: "u6-w9",
      japanese: jp(r("買います", "かいます", "买")),
      kana: "かいます",
      meaning: "买",
      partOfSpeech: "动词",
      example: jp(r("店", "みせ", "商店"), p("で"), r("飲み物", "のみもの", "饮料"), p("を"), r("買います", "かいます", "买"), p("。")),
      exampleMeaning: "在店里买饮料。",
    },
    {
      id: "u6-w10",
      japanese: jp(r("話します", "はなします", "说话")),
      kana: "はなします",
      meaning: "说话",
      partOfSpeech: "动词",
      example: jp(r("教室", "きょうしつ", "教室"), p("で"), r("日本語", "にほんご", "日语"), p("を"), r("話します", "はなします", "说话"), p("。")),
      exampleMeaning: "在教室说日语。",
    },
  ],
  grammar: [
    {
      id: "u6-g1",
      title: "宾语 を",
      structure: jp(p("名词 + を + "), r("動詞", "どうし", "动词")),
      explanation: "「を」标记动作对象，例如吃什么、读什么、写什么。",
      usage: "「を」在这里读作 o。",
      examples: [
        { japanese: jp(r("朝ご飯", "あさごはん", "早饭"), p("を"), r("食べます", "たべます", "吃"), p("。")), meaning: "吃早饭。" },
        { japanese: jp(r("手紙", "てがみ", "信"), p("を"), r("書きます", "かきます", "写"), p("。")), meaning: "写信。" },
      ],
    },
    {
      id: "u6-g2",
      title: "动作场所 で",
      structure: jp(p("地点 + で + "), r("動詞", "どうし", "动词")),
      explanation: "「で」表示动作发生的场所。",
      usage: "如果只是说明某物存在的位置，通常不用这个「で」。",
      examples: [
        { japanese: jp(r("家", "いえ", "家"), p("で"), r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。")), meaning: "在家读书。" },
        { japanese: jp(r("店", "みせ", "商店"), p("でパンを"), r("買います", "かいます", "买"), p("。")), meaning: "在店里买面包。" },
      ],
    },
    {
      id: "u6-g3",
      title: "时间点 に",
      structure: jp(p("时间 + に + "), r("動詞", "どうし", "动词")),
      explanation: "「に」可标记具体时间点，如几点、星期几。",
      usage: "「朝」「今日」这类较宽泛时间词常不加「に」。",
      examples: [
        { japanese: jp(r("七時", "しちじ", "七点"), p("に"), r("起きます", "おきます", "起床"), p("。")), meaning: "七点起床。" },
        { japanese: jp(r("土曜日", "どようび", "星期六"), p("に"), r("来ます", "きます", "来"), p("。")), meaning: "星期六来。" },
      ],
    },
    {
      id: "u6-g4",
      title: "目的地 に",
      structure: jp(p("地点 + に + "), r("行きます", "いきます", "去")),
      explanation: "「に」也可表示移动的到达点或目的地。",
      usage: "初级阶段也会看到「へ」，这里先掌握「に」的基础目的地用法。",
      examples: [
        { japanese: jp(r("駅", "えき", "车站"), p("に"), r("行きます", "いきます", "去"), p("。")), meaning: "去车站。" },
        { japanese: jp(r("教室", "きょうしつ", "教室"), p("に"), r("来ます", "きます", "来"), p("。")), meaning: "来教室。" },
      ],
    },
  ],
  examples: [
    { japanese: jp(r("教室", "きょうしつ", "教室"), p("で"), r("日本語", "にほんご", "日语"), p("を"), r("勉強", "べんきょう", "学习"), p("します。")), meaning: "在教室学习日语。" },
    { japanese: jp(r("家", "いえ", "家"), p("で"), r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。")), meaning: "在家读书。" },
    { japanese: jp(r("七時", "しちじ", "七点"), p("に"), r("起きます", "おきます", "起床"), p("。")), meaning: "七点起床。" },
    { japanese: jp(r("駅", "えき", "车站"), p("に"), r("行きます", "いきます", "去"), p("。")), meaning: "去车站。" },
    { japanese: jp(r("店", "みせ", "商店"), p("で"), r("飲み物", "のみもの", "饮料"), p("を"), r("買います", "かいます", "买"), p("。")), meaning: "在店里买饮料。" },
    { japanese: jp(r("公園", "こうえん", "公园"), p("で"), r("友達", "ともだち", "朋友"), p("と"), r("話します", "はなします", "说话"), p("。")), meaning: "在公园和朋友说话。" },
  ],
  reading: {
    title: "周末的小安排",
    intro: "朋友之间确认周末在哪里见面、做什么。",
    lines: [
      {
        speaker: "陳",
        japanese: jp(r("土曜日", "どようび", "星期六"), p("に"), r("公園", "こうえん", "公园"), p("に"), r("行きます", "いきます", "去"), p("か。")),
        meaning: "星期六去公园吗？",
        keywords: [{ term: "公園", reading: "こうえん", meaning: "公园" }],
      },
      {
        speaker: "葵",
        japanese: jp(p("はい。"), r("公園", "こうえん", "公园"), p("で"), r("友達", "ともだち", "朋友"), p("と"), r("話します", "はなします", "说话"), p("。")),
        meaning: "去。在公园和朋友说话。",
        keywords: [{ term: "話します", reading: "はなします", meaning: "说话" }],
      },
      {
        speaker: "陳",
        japanese: jp(r("朝", "あさ", "早晨"), p("は"), r("何", "なに", "什么"), p("を"), r("食べます", "たべます", "吃"), p("か。")),
        meaning: "早上吃什么？",
        keywords: [{ term: "何", reading: "なに", meaning: "什么" }],
      },
      {
        speaker: "葵",
        japanese: jp(r("朝", "あさ", "早晨"), p("はパンを"), r("食べます", "たべます", "吃"), p("。")),
        meaning: "早上吃面包。",
        keywords: [{ term: "朝ご飯", reading: "あさごはん", meaning: "早饭" }],
      },
      {
        speaker: "陳",
        japanese: jp(p("そのあと、"), r("店", "みせ", "商店"), p("でコーヒーを"), r("買います", "かいます", "买"), p("。")),
        meaning: "之后，在店里买咖啡。",
        keywords: [{ term: "買います", reading: "かいます", meaning: "买" }],
      },
    ],
  },
  exercises: [
    {
      id: "u6-e1",
      type: "multiple-choice",
      prompt: jp(r("本", "ほん", "书"), p(" ___ "), r("読みます", "よみます", "读"), p("。应填哪个助词？")),
      options: ["を", "で", "に", "の"],
      correctAnswer: "を",
      explanation: jp(r("本", "ほん", "书"), p("是"), r("読みます", "よみます", "读"), p("的对象，所以用「を」。")),
    },
    {
      id: "u6-e2",
      type: "fill-blank",
      prompt: jp(r("教室", "きょうしつ", "教室"), p(" ____ "), r("日本語", "にほんご", "日语"), p("を"), r("勉強", "べんきょう", "学习"), p("します。")),
      correctAnswer: "で",
      explanation: jp(r("教室", "きょうしつ", "教室"), p("是动作发生的场所，用「で」。")),
    },
    {
      id: "u6-e3",
      type: "order-sentence",
      prompt: jp(p("排列成“七点起床”。")),
      parts: [r("七時", "しちじ", "七点"), r("起きます", "おきます", "起床"), p("に")],
      correctOrder: [r("七時", "しちじ", "七点"), p("に"), r("起きます", "おきます", "起床")],
      explanation: jp(r("七時", "しちじ", "七点"), p("是具体时间点，后接「に」。")),
    },
    {
      id: "u6-e4",
      type: "true-false",
      prompt: jp(p("判断助词。")),
      statement: jp(r("店", "みせ", "商店"), p("でパンを"), r("買います", "かいます", "买"), p("。这里的「で」表示动作场所。")),
      correctAnswer: true,
      explanation: jp(r("店", "みせ", "商店"), p("是买东西的地点，所以用「で」。")),
    },
    {
      id: "u6-e5",
      type: "matching",
      prompt: jp(p("匹配助词和基础功能。")),
      pairs: [
        { left: "を", right: "动作对象" },
        { left: "で", right: "动作场所" },
        { left: "に（七時に）", right: "时间点" },
        { left: "に（駅に）", right: "目的地" },
      ],
      explanation: jp(p("同一个「に」可以标记时间点，也可以标记目的地。")),
    },
    {
      id: "u6-e6",
      type: "multiple-choice",
      prompt: jp(r("駅", "えき", "车站"), p(" ___ "), r("行きます", "いきます", "去"), p("。应填哪个助词？")),
      options: ["に", "を", "で", "と"],
      correctAnswer: "に",
      explanation: jp(r("駅", "えき", "车站"), p("是目的地，用「に」。")),
    },
    {
      id: "u6-e7",
      type: "fill-blank",
      prompt: jp(r("手紙", "てがみ", "信"), p(" ____ "), r("書きます", "かきます", "写"), p("。")),
      correctAnswer: "を",
      explanation: jp(r("手紙", "てがみ", "信"), p("是动作对象，用「を」。")),
    },
    {
      id: "u6-e8",
      type: "true-false",
      prompt: jp(p("判断句意。")),
      statement: jp(r("家", "いえ", "家"), p("で"), r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。表示“在家读书”。")),
      correctAnswer: true,
      explanation: jp(r("家", "いえ", "家"), p("で表示读书的地点。")),
    },
    {
      id: "u6-e9",
      type: "order-sentence",
      prompt: jp(p("排列成“在公园说话”。")),
      parts: [r("公園", "こうえん", "公园"), r("話します", "はなします", "说话"), p("で")],
      correctOrder: [r("公園", "こうえん", "公园"), p("で"), r("話します", "はなします", "说话")],
      explanation: jp(p("动作场所放在动词前，用「で」标记。")),
    },
    {
      id: "u6-e10",
      type: "multiple-choice",
      prompt: jp(p("哪一句表示“在店里买饮料”？")),
      options: [
        jp(r("店", "みせ", "商店"), p("で"), r("飲み物", "のみもの", "饮料"), p("を"), r("買います", "かいます", "买"), p("。")),
        jp(r("店", "みせ", "商店"), p("に"), r("飲み物", "のみもの", "饮料"), p("を"), r("買います", "かいます", "买"), p("。")),
        jp(r("飲み物", "のみもの", "饮料"), p("で"), r("店", "みせ", "商店"), p("を"), r("買います", "かいます", "买"), p("。")),
        jp(r("店", "みせ", "商店"), p("を"), r("買います", "かいます", "买"), p("。")),
      ],
      correctAnswer: jp(r("店", "みせ", "商店"), p("で"), r("飲み物", "のみもの", "饮料"), p("を"), r("買います", "かいます", "买"), p("。")),
      explanation: jp(r("店", "みせ", "商店"), p("是动作场所，用「で」；"), r("飲み物", "のみもの", "饮料"), p("是对象，用「を」。")),
    },
  ],
};
