import type { Lesson } from "../types";

export const unit1: Lesson = {
  id: "unit-1",
  unit: 1,
  title: "A は B です",
  subtitle: "介绍自己，也认识别人",
  description:
    "学习日语最基础的判断句，用主题助词「は」进行自我介绍、说明身份并提出简单问题。",
  duration: "约 40 分钟",
  accent: "#547f74",
  goals: [
    "用「A は B です」说明身份或属性",
    "使用「ではありません」进行礼貌否定",
    "用「か」提出判断问句并自然回答",
  ],
  vocabulary: [
    {
      id: "u1-w1",
      japanese: "私",
      kana: "わたし",
      meaning: "我",
      partOfSpeech: "代词",
      example: "私は陳です。",
      exampleMeaning: "我是小陈。",
    },
    {
      id: "u1-w2",
      japanese: "学生",
      kana: "がくせい",
      meaning: "学生",
      partOfSpeech: "名词",
      example: "妹は大学の学生です。",
      exampleMeaning: "妹妹是大学生。",
    },
    {
      id: "u1-w3",
      japanese: "先生",
      kana: "せんせい",
      meaning: "老师；先生",
      partOfSpeech: "名词",
      example: "佐藤さんは日本語の先生です。",
      exampleMeaning: "佐藤老师是日语老师。",
    },
    {
      id: "u1-w4",
      japanese: "会社員",
      kana: "かいしゃいん",
      meaning: "公司职员",
      partOfSpeech: "名词",
      example: "父は会社員です。",
      exampleMeaning: "父亲是公司职员。",
    },
    {
      id: "u1-w5",
      japanese: "大学",
      kana: "だいがく",
      meaning: "大学",
      partOfSpeech: "名词",
      example: "この大学は静かです。",
      exampleMeaning: "这所大学很安静。",
    },
    {
      id: "u1-w6",
      japanese: "中国",
      kana: "ちゅうごく",
      meaning: "中国",
      partOfSpeech: "专有名词",
      example: "私は中国から来ました。",
      exampleMeaning: "我来自中国。",
    },
    {
      id: "u1-w7",
      japanese: "日本",
      kana: "にほん",
      meaning: "日本",
      partOfSpeech: "专有名词",
      example: "日本の冬は地域で違います。",
      exampleMeaning: "日本的冬天因地区而异。",
    },
    {
      id: "u1-w8",
      japanese: "友達",
      kana: "ともだち",
      meaning: "朋友",
      partOfSpeech: "名词",
      example: "高橋さんは大学の友達です。",
      exampleMeaning: "高桥是大学时的朋友。",
    },
    {
      id: "u1-w9",
      japanese: "名前",
      kana: "なまえ",
      meaning: "名字",
      partOfSpeech: "名词",
      example: "私の名前は林です。",
      exampleMeaning: "我的名字是小林。",
    },
    {
      id: "u1-w10",
      japanese: "専攻",
      kana: "せんこう",
      meaning: "专业",
      partOfSpeech: "名词",
      example: "専攻はデザインです。",
      exampleMeaning: "专业是设计。",
    },
  ],
  grammar: [
    {
      id: "u1-g1",
      title: "判断句",
      structure: "A は B です",
      explanation:
        "助词「は」提示谈论的主题，「です」构成礼貌的判断。这里的「は」读作 wa。",
      usage:
        "可用于身份、职业、国籍等说明。日语中语境明确时，A 可以省略。",
      examples: [
        { japanese: "私は留学生です。", meaning: "我是留学生。" },
        { japanese: "田中さんは先生です。", meaning: "田中先生是老师。" },
        { japanese: "専攻は建築です。", meaning: "专业是建筑。" },
      ],
    },
    {
      id: "u1-g2",
      title: "礼貌否定",
      structure: "A は B ではありません",
      explanation:
        "「ではありません」是「です」的礼貌否定形式，表示“不是……”。口语中也常说「じゃありません」。",
      usage:
        "用于正式或初次交流。回答问题时可先说「いいえ」再补充否定句。",
      examples: [
        { japanese: "私は先生ではありません。", meaning: "我不是老师。" },
        { japanese: "ここは教室ではありません。", meaning: "这里不是教室。" },
      ],
    },
    {
      id: "u1-g3",
      title: "判断问句",
      structure: "A は B ですか",
      explanation:
        "在句末加「か」即可构成礼貌问句。书写时即使不用问号，也能表达疑问。",
      usage:
        "肯定回答常用「はい、そうです」，否定回答常用「いいえ、違います」或完整否定句。",
      examples: [
        { japanese: "李さんは学生ですか。", meaning: "小李是学生吗？" },
        { japanese: "はい、そうです。", meaning: "是的，没错。" },
        { japanese: "いいえ、会社員です。", meaning: "不，是公司职员。" },
      ],
    },
    {
      id: "u1-g4",
      title: "名词所属",
      structure: "A の B",
      explanation:
        "助词「の」连接两个名词，表示所属、类别或内容，可理解为“的”。",
      usage:
        "A 对 B 作进一步限定，例如所属机构、国家或专业领域。",
      examples: [
        { japanese: "桜大学の学生", meaning: "樱大学的学生" },
        { japanese: "日本語の先生", meaning: "日语老师" },
      ],
    },
  ],
  examples: [
    { japanese: "私は周です。", kana: "わたしはしゅうです。", meaning: "我是小周。" },
    { japanese: "木村さんは会社員です。", meaning: "木村先生是公司职员。" },
    { japanese: "私は先生ではありません。", meaning: "我不是老师。" },
    { japanese: "林さんは学生ですか。", meaning: "小林是学生吗？" },
    { japanese: "専攻は情報デザインです。", meaning: "专业是信息设计。" },
    { japanese: "王さんは大学の友達です。", meaning: "小王是大学时的朋友。" },
  ],
  reading: {
    title: "新しいクラス",
    intro: "新学期第一天，两位同学在教室里认识彼此。",
    lines: [
      {
        speaker: "美咲",
        japanese: "はじめまして。私は森美咲です。",
        meaning: "初次见面。我叫森美咲。",
        keywords: [
          { term: "はじめまして", reading: "はじめまして", meaning: "初次见面" },
          { term: "私", reading: "わたし", meaning: "我" },
        ],
      },
      {
        speaker: "浩然",
        japanese: "はじめまして。趙浩然です。",
        meaning: "初次见面。我叫赵浩然。",
        keywords: [],
      },
      {
        speaker: "美咲",
        japanese: "趙さんは留学生ですか。",
        meaning: "赵同学是留学生吗？",
        keywords: [{ term: "留学生", reading: "りゅうがくせい", meaning: "留学生" }],
      },
      {
        speaker: "浩然",
        japanese: "はい、中国からの留学生です。専攻は建築です。",
        meaning: "是的，我是来自中国的留学生。专业是建筑。",
        keywords: [
          { term: "中国", reading: "ちゅうごく", meaning: "中国" },
          { term: "建築", reading: "けんちく", meaning: "建筑" },
        ],
      },
      {
        speaker: "美咲",
        japanese: "そうですか。私はデザイン専攻です。",
        meaning: "这样啊。我是设计专业。",
        keywords: [{ term: "そうですか", reading: "そうですか", meaning: "这样啊" }],
      },
    ],
  },
  exercises: [
    {
      id: "u1-e1",
      type: "multiple-choice",
      prompt: "选择正确的助词：私 ___ 学生です。",
      options: ["は", "の", "か", "を"],
      correctAnswer: "は",
      explanation: "「は」提示句子的主题，写作「は」但在这里读作 wa。",
    },
    {
      id: "u1-e2",
      type: "fill-blank",
      prompt: "补全礼貌判断句：田中さんは先生 ____。",
      correctAnswer: "です",
      explanation: "名词判断句的礼貌肯定形式以「です」结尾。",
    },
    {
      id: "u1-e3",
      type: "order-sentence",
      prompt: "排列成“我是大学生”。",
      parts: ["大学生", "私", "です", "は"],
      correctOrder: ["私", "は", "大学生", "です"],
      explanation: "基本语序是「主题 + は + 身份 + です」。",
    },
    {
      id: "u1-e4",
      type: "true-false",
      prompt: "判断句子是否符合语法。",
      statement: "「私は会社員ではありません」表示“我是公司职员”。",
      correctAnswer: false,
      explanation: "「ではありません」表示否定，因此句意是“我不是公司职员”。",
    },
    {
      id: "u1-e5",
      type: "multiple-choice",
      prompt: "怎样问“佐藤先生是老师吗？”",
      options: [
        "佐藤さんは先生ですか。",
        "佐藤さんの先生です。",
        "佐藤さんは先生かです。",
        "先生は佐藤さんのか。",
      ],
      correctAnswer: "佐藤さんは先生ですか。",
      explanation: "在礼貌判断句末尾加「か」构成问句。",
    },
    {
      id: "u1-e6",
      type: "matching",
      prompt: "匹配词语与中文意思。",
      pairs: [
        { left: "学生", right: "学生" },
        { left: "先生", right: "老师" },
        { left: "会社員", right: "公司职员" },
        { left: "専攻", right: "专业" },
      ],
      explanation: "这些词常用于自我介绍和询问身份。",
    },
    {
      id: "u1-e7",
      type: "fill-blank",
      prompt: "补全否定句：私は先生では ____。",
      correctAnswer: "ありません",
      explanation: "「ではありません」是礼貌否定形式。",
    },
    {
      id: "u1-e8",
      type: "multiple-choice",
      prompt: "「桜大学の学生」中的「の」表示什么？",
      options: ["所属或限定", "提问", "否定", "动作对象"],
      correctAnswer: "所属或限定",
      explanation: "「の」连接名词，前面的名词对后面的名词作所属或类别限定。",
    },
    {
      id: "u1-e9",
      type: "order-sentence",
      prompt: "排列成“专业是设计”。",
      parts: ["デザイン", "専攻", "です", "は"],
      correctOrder: ["専攻", "は", "デザイン", "です"],
      explanation: "当语境明确时，不必重复「私の」。",
    },
    {
      id: "u1-e10",
      type: "true-false",
      prompt: "判断助词读音。",
      statement: "在「私は学生です」中，助词「は」读作 wa。",
      correctAnswer: true,
      explanation: "作为主题助词时，「は」读作 wa。",
    },
  ],
};
