import type { Lesson } from "../types";
import { jp, p, r } from "./text";

export const unit5: Lesson = {
  id: "unit-5",
  unit: 5,
  title: "动词ます形与日常动作",
  subtitle: "用礼貌动词说出每天做的事",
  description:
    "学习常见动词的ます形，用简单句子表达吃、喝、看、听、读、写、去、来和做。",
  duration: "约 45 分钟",
  accent: "#c36f5c",
  goals: [
    "认识常见日常动作动词的ます形",
    "用「名词を动词ます」表达动作对象",
    "用「行きます・来ます・します」说出简单安排",
  ],
  vocabulary: [
    {
      id: "u5-w1",
      japanese: jp(r("食べます", "たべます", "吃")),
      kana: "たべます",
      meaning: "吃",
      partOfSpeech: "动词",
      example: jp(r("朝", "あさ", "早晨"), p("、パンを"), r("食べます", "たべます", "吃"), p("。")),
      exampleMeaning: "早上吃面包。",
    },
    {
      id: "u5-w2",
      japanese: jp(r("飲みます", "のみます", "喝")),
      kana: "のみます",
      meaning: "喝",
      partOfSpeech: "动词",
      example: jp(p("コーヒーを"), r("飲みます", "のみます", "喝"), p("。")),
      exampleMeaning: "喝咖啡。",
    },
    {
      id: "u5-w3",
      japanese: jp(r("見ます", "みます", "看")),
      kana: "みます",
      meaning: "看",
      partOfSpeech: "动词",
      example: jp(r("夜", "よる", "夜晚"), p("、"), r("映画", "えいが", "电影"), p("を"), r("見ます", "みます", "看"), p("。")),
      exampleMeaning: "晚上看电影。",
    },
    {
      id: "u5-w4",
      japanese: jp(r("聞きます", "ききます", "听；询问")),
      kana: "ききます",
      meaning: "听；询问",
      partOfSpeech: "动词",
      example: jp(r("音楽", "おんがく", "音乐"), p("を"), r("聞きます", "ききます", "听"), p("。")),
      exampleMeaning: "听音乐。",
    },
    {
      id: "u5-w5",
      japanese: jp(r("読みます", "よみます", "读")),
      kana: "よみます",
      meaning: "读",
      partOfSpeech: "动词",
      example: jp(r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。")),
      exampleMeaning: "读书。",
    },
    {
      id: "u5-w6",
      japanese: jp(r("書きます", "かきます", "写")),
      kana: "かきます",
      meaning: "写",
      partOfSpeech: "动词",
      example: jp(r("名前", "なまえ", "名字"), p("を"), r("書きます", "かきます", "写"), p("。")),
      exampleMeaning: "写名字。",
    },
    {
      id: "u5-w7",
      japanese: jp(r("行きます", "いきます", "去")),
      kana: "いきます",
      meaning: "去",
      partOfSpeech: "动词",
      example: jp(r("午後", "ごご", "下午"), p("、"), r("図書館", "としょかん", "图书馆"), p("へ"), r("行きます", "いきます", "去"), p("。")),
      exampleMeaning: "下午去图书馆。",
    },
    {
      id: "u5-w8",
      japanese: jp(r("来ます", "きます", "来")),
      kana: "きます",
      meaning: "来",
      partOfSpeech: "动词",
      example: jp(r("友達", "ともだち", "朋友"), p("が"), r("教室", "きょうしつ", "教室"), p("に"), r("来ます", "きます", "来"), p("。")),
      exampleMeaning: "朋友来教室。",
    },
    {
      id: "u5-w9",
      japanese: "します",
      kana: "します",
      meaning: "做",
      partOfSpeech: "动词",
      example: jp(r("夜", "よる", "夜晚"), p("、"), r("勉強", "べんきょう", "学习"), p("をします。")),
      exampleMeaning: "晚上学习。",
    },
    {
      id: "u5-w10",
      japanese: jp(r("宿題", "しゅくだい", "作业")),
      kana: "しゅくだい",
      meaning: "作业",
      partOfSpeech: "名词",
      example: jp(r("宿題", "しゅくだい", "作业"), p("をします。")),
      exampleMeaning: "做作业。",
    },
  ],
  grammar: [
    {
      id: "u5-g1",
      title: "礼貌动词ます形",
      structure: jp(r("食べます", "たべます", "吃"), p(" / "), r("飲みます", "のみます", "喝")),
      explanation: "ます形是礼貌的现在或习惯动作表达，适合课堂和初次交流。",
      usage: "本课先把动词作为固定表达记住，不深入动词分类。",
      examples: [
        { japanese: jp(p("パンを"), r("食べます", "たべます", "吃"), p("。")), meaning: "吃面包。" },
        { japanese: jp(r("お茶", "おちゃ", "茶"), p("を"), r("飲みます", "のみます", "喝"), p("。")), meaning: "喝茶。" },
      ],
    },
    {
      id: "u5-g2",
      title: "动作对象",
      structure: jp(p("名词 + を + "), r("動詞", "どうし", "动词"), p("ます")),
      explanation: "助词「を」标记动作直接作用的对象，如书、音乐、电影等。",
      usage: "「を」写作を，在这里通常读作 o。",
      examples: [
        { japanese: jp(r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。")), meaning: "读书。" },
        { japanese: jp(r("音楽", "おんがく", "音乐"), p("を"), r("聞きます", "ききます", "听"), p("。")), meaning: "听音乐。" },
      ],
    },
    {
      id: "u5-g3",
      title: "去、来、做",
      structure: jp(r("行きます", "いきます", "去"), p(" / "), r("来ます", "きます", "来"), p(" / します")),
      explanation: "「行きます」表示去某处，「来ます」表示来到说话人所在或相关地点，「します」表示做某事。",
      usage: "地点常和「へ」或「に」一起出现，本课先用基础例句熟悉。",
      examples: [
        { japanese: jp(r("学校", "がっこう", "学校"), p("へ"), r("行きます", "いきます", "去"), p("。")), meaning: "去学校。" },
        { japanese: jp(r("日本語", "にほんご", "日语"), p("の"), r("勉強", "べんきょう", "学习"), p("をします。")), meaning: "学习日语。" },
      ],
    },
  ],
  examples: [
    { japanese: jp(r("朝", "あさ", "早晨"), p("、パンを"), r("食べます", "たべます", "吃"), p("。")), meaning: "早上吃面包。" },
    { japanese: jp(p("コーヒーを"), r("飲みます", "のみます", "喝"), p("。")), meaning: "喝咖啡。" },
    { japanese: jp(r("日本語", "にほんご", "日语"), p("の"), r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。")), meaning: "读日语书。" },
    { japanese: jp(r("名前", "なまえ", "名字"), p("を"), r("書きます", "かきます", "写"), p("。")), meaning: "写名字。" },
    { japanese: jp(r("午後", "ごご", "下午"), p("、"), r("学校", "がっこう", "学校"), p("へ"), r("行きます", "いきます", "去"), p("。")), meaning: "下午去学校。" },
    { japanese: jp(r("夜", "よる", "夜晚"), p("、"), r("宿題", "しゅくだい", "作业"), p("をします。")), meaning: "晚上做作业。" },
  ],
  reading: {
    title: "课后安排",
    intro: "两位同学在课后聊今天要做的事。",
    lines: [
      {
        speaker: "葵",
        japanese: jp(r("今日", "きょう", "今天"), p("、"), r("図書館", "としょかん", "图书馆"), p("へ"), r("行きます", "いきます", "去"), p("か。")),
        meaning: "今天去图书馆吗？",
        keywords: [
          { term: "今日", reading: "きょう", meaning: "今天" },
          { term: "図書館", reading: "としょかん", meaning: "图书馆" },
        ],
      },
      {
        speaker: "陳",
        japanese: jp(p("はい、"), r("行きます", "いきます", "去"), p("。そこで"), r("日本語", "にほんご", "日语"), p("の"), r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。")),
        meaning: "去。我在那里读日语书。",
        keywords: [{ term: "読みます", reading: "よみます", meaning: "读" }],
      },
      {
        speaker: "葵",
        japanese: jp(p("いいですね。わたしは"), r("音楽", "おんがく", "音乐"), p("を"), r("聞きます", "ききます", "听"), p("。")),
        meaning: "不错呢。我听音乐。",
        keywords: [{ term: "音楽", reading: "おんがく", meaning: "音乐" }],
      },
      {
        speaker: "陳",
        japanese: jp(r("夜", "よる", "夜晚"), p("は"), r("宿題", "しゅくだい", "作业"), p("をしますか。")),
        meaning: "晚上做作业吗？",
        keywords: [{ term: "宿題", reading: "しゅくだい", meaning: "作业" }],
      },
      {
        speaker: "葵",
        japanese: jp(p("はい。"), r("短い", "みじかい", "短的"), r("文", "ぶん", "句子"), p("を"), r("書きます", "かきます", "写"), p("。")),
        meaning: "做。写短句。",
        keywords: [
          { term: "短い", reading: "みじかい", meaning: "短的" },
          { term: "文", reading: "ぶん", meaning: "句子" },
        ],
      },
    ],
  },
  exercises: [
    {
      id: "u5-e1",
      type: "multiple-choice",
      prompt: jp(p("选择“吃”的日语。")),
      options: [jp(r("食べます", "たべます", "吃")), jp(r("飲みます", "のみます", "喝")), jp(r("読みます", "よみます", "读")), jp(r("聞きます", "ききます", "听"))],
      correctAnswer: jp(r("食べます", "たべます", "吃")),
      explanation: jp(r("食べます", "たべます", "吃"), p("表示“吃”。")),
    },
    {
      id: "u5-e2",
      type: "fill-blank",
      prompt: jp(r("本", "ほん", "书"), p("を ____。")),
      correctAnswer: "読みます",
      explanation: jp(r("本", "ほん", "书"), p("搭配"), r("読みます", "よみます", "读"), p("，表示“读书”。")),
    },
    {
      id: "u5-e3",
      type: "order-sentence",
      prompt: jp(p("排列成“喝咖啡”。")),
      parts: [r("飲みます", "のみます", "喝"), p("コーヒー"), p("を")],
      correctOrder: [p("コーヒー"), p("を"), r("飲みます", "のみます", "喝")],
      explanation: jp(p("动作对象后接「を」，再接动词ます形。")),
    },
    {
      id: "u5-e4",
      type: "true-false",
      prompt: jp(p("判断句意。")),
      statement: jp(r("音楽", "おんがく", "音乐"), p("を"), r("聞きます", "ききます", "听"), p("。表示“听音乐”。")),
      correctAnswer: true,
      explanation: jp(r("聞きます", "ききます", "听"), p("表示“听”。")),
    },
    {
      id: "u5-e5",
      type: "matching",
      prompt: jp(p("匹配动词和中文意思。")),
      pairs: [
        { left: jp(r("見ます", "みます", "看")), right: "看" },
        { left: jp(r("書きます", "かきます", "写")), right: "写" },
        { left: jp(r("来ます", "きます", "来")), right: "来" },
        { left: "します", right: "做" },
      ],
      explanation: jp(p("这些都是常见日常动作的ます形。")),
    },
    {
      id: "u5-e6",
      type: "multiple-choice",
      prompt: jp(r("学校", "がっこう", "学校"), p("へ ____。最自然的是哪一项？")),
      options: [jp(r("行きます", "いきます", "去")), jp(r("飲みます", "のみます", "喝")), jp(r("聞きます", "ききます", "听")), jp(r("書きます", "かきます", "写"))],
      correctAnswer: jp(r("行きます", "いきます", "去")),
      explanation: jp(p("去某地用"), r("行きます", "いきます", "去"), p("。")),
    },
    {
      id: "u5-e7",
      type: "fill-blank",
      prompt: jp(r("名前", "なまえ", "名字"), p("を ____。")),
      correctAnswer: "書きます",
      explanation: jp(r("名前", "なまえ", "名字"), p("可以和"), r("書きます", "かきます", "写"), p("搭配。")),
    },
    {
      id: "u5-e8",
      type: "true-false",
      prompt: jp(p("判断用法。")),
      statement: jp(p("「コーヒーを"), r("飲みます", "のみます", "喝"), p("」表示“喝咖啡”。")),
      correctAnswer: true,
      explanation: jp(r("飲みます", "のみます", "喝"), p("表示喝饮料。")),
    },
    {
      id: "u5-e9",
      type: "order-sentence",
      prompt: jp(p("排列成“晚上做作业”。")),
      parts: [r("夜", "よる", "夜晚"), r("宿題", "しゅくだい", "作业"), p("します"), p("を")],
      correctOrder: [r("夜", "よる", "夜晚"), r("宿題", "しゅくだい", "作业"), p("を"), p("します")],
      explanation: jp(r("宿題", "しゅくだい", "作业"), p("をします，表示“做作业”。")),
    },
    {
      id: "u5-e10",
      type: "multiple-choice",
      prompt: jp(p("哪一句表示“看电影”？")),
      options: [
        jp(r("映画", "えいが", "电影"), p("を"), r("見ます", "みます", "看"), p("。")),
        jp(r("映画", "えいが", "电影"), p("を"), r("聞きます", "ききます", "听"), p("。")),
        jp(r("映画", "えいが", "电影"), p("を"), r("書きます", "かきます", "写"), p("。")),
        jp(r("映画", "えいが", "电影"), p("をします。")),
      ],
      correctAnswer: jp(r("映画", "えいが", "电影"), p("を"), r("見ます", "みます", "看"), p("。")),
      explanation: jp(r("映画", "えいが", "电影"), p("通常搭配"), r("見ます", "みます", "看"), p("。")),
    },
  ],
};
