import type { Lesson } from "../types";
import { jp, p, r } from "./text";

export const unit7: Lesson = {
  id: "unit-7",
  unit: 7,
  title: "形容词入门",
  subtitle: "描述事物、人和场所",
  description:
    "学习い形容词和な形容词的基础用法，用简单肯定句和否定句描述身边的东西。",
  duration: "约 45 分钟",
  accent: "#d49b42",
  goals: [
    "区分い形容词和な形容词",
    "用形容词肯定句描述名词",
    "说出基础的形容词否定句",
  ],
  vocabulary: [
    {
      id: "u7-w1",
      japanese: jp(r("大きい", "おおきい", "大的")),
      kana: "おおきい",
      meaning: "大的",
      partOfSpeech: "い形容词",
      example: jp(r("この", "この", "这个"), r("教室", "きょうしつ", "教室"), p("は"), r("大きい", "おおきい", "大的"), p("です。")),
      exampleMeaning: "这间教室很大。",
    },
    {
      id: "u7-w2",
      japanese: jp(r("小さい", "ちいさい", "小的")),
      kana: "ちいさい",
      meaning: "小的",
      partOfSpeech: "い形容词",
      example: jp(r("この", "この", "这个"), r("鞄", "かばん", "包"), p("は"), r("小さい", "ちいさい", "小的"), p("です。")),
      exampleMeaning: "这个包很小。",
    },
    {
      id: "u7-w3",
      japanese: jp(r("新しい", "あたらしい", "新的")),
      kana: "あたらしい",
      meaning: "新的",
      partOfSpeech: "い形容词",
      example: jp(r("新しい", "あたらしい", "新的"), r("本", "ほん", "书"), p("を"), r("読みます", "よみます", "读"), p("。")),
      exampleMeaning: "读新书。",
    },
    {
      id: "u7-w4",
      japanese: jp(r("古い", "ふるい", "旧的；古老的")),
      kana: "ふるい",
      meaning: "旧的；古老的",
      partOfSpeech: "い形容词",
      example: jp(r("この", "この", "这个"), r("時計", "とけい", "钟；表"), p("は"), r("古い", "ふるい", "旧的"), p("です。")),
      exampleMeaning: "这块表很旧。",
    },
    {
      id: "u7-w5",
      japanese: jp(r("高い", "たかい", "贵的；高的")),
      kana: "たかい",
      meaning: "贵的；高的",
      partOfSpeech: "い形容词",
      example: jp(p("このコーヒーは"), r("高い", "たかい", "贵的"), p("です。")),
      exampleMeaning: "这杯咖啡很贵。",
    },
    {
      id: "u7-w6",
      japanese: jp(r("安い", "やすい", "便宜的")),
      kana: "やすい",
      meaning: "便宜的",
      partOfSpeech: "い形容词",
      example: jp(r("この", "この", "这个"), r("店", "みせ", "商店"), p("のパンは"), r("安い", "やすい", "便宜的"), p("です。")),
      exampleMeaning: "这家店的面包很便宜。",
    },
    {
      id: "u7-w7",
      japanese: "おいしい",
      kana: "おいしい",
      meaning: "好吃的",
      partOfSpeech: "い形容词",
      example: jp(p("このパンはおいしいです。")),
      exampleMeaning: "这个面包很好吃。",
    },
    {
      id: "u7-w8",
      japanese: jp(r("静か", "しずか", "安静")),
      kana: "しずか",
      meaning: "安静",
      partOfSpeech: "な形容词",
      example: jp(r("図書館", "としょかん", "图书馆"), p("は"), r("静か", "しずか", "安静"), p("です。")),
      exampleMeaning: "图书馆很安静。",
    },
    {
      id: "u7-w9",
      japanese: jp(r("便利", "べんり", "方便")),
      kana: "べんり",
      meaning: "方便",
      partOfSpeech: "な形容词",
      example: jp(r("駅", "えき", "车站"), p("の"), r("近く", "ちかく", "附近"), p("は"), r("便利", "べんり", "方便"), p("です。")),
      exampleMeaning: "车站附近很方便。",
    },
    {
      id: "u7-w10",
      japanese: "きれい",
      kana: "きれい",
      meaning: "漂亮；干净",
      partOfSpeech: "な形容词",
      example: jp(p("このノートはきれいです。")),
      exampleMeaning: "这本笔记本很漂亮。",
    },
  ],
  grammar: [
    {
      id: "u7-g1",
      title: "い形容词肯定句",
      structure: jp(r("名詞", "めいし", "名词"), p("は い形容词 です")),
      explanation: "い形容词可以直接放在「です」前，描述名词的性质。",
      usage: "常见词有「大きい」「新しい」「おいしい」等。",
      examples: [
        { japanese: jp(r("この", "この", "这个"), r("本", "ほん", "书"), p("は"), r("新しい", "あたらしい", "新的"), p("です。")), meaning: "这本书是新的。" },
        { japanese: jp(p("このパンはおいしいです。")), meaning: "这个面包很好吃。" },
      ],
    },
    {
      id: "u7-g2",
      title: "い形容词否定句",
      structure: jp(r("高い", "たかい", "贵的"), p(" → "), r("高くない", "たかくない", "不贵"), p("です")),
      explanation: "基础否定可把词尾「い」变为「くないです」。",
      usage: "「いい」的变化特殊，本课暂不展开。",
      examples: [
        { japanese: jp(p("このコーヒーは"), r("高くない", "たかくない", "不贵"), p("です。")), meaning: "这杯咖啡不贵。" },
        { japanese: jp(r("この", "この", "这个"), r("鞄", "かばん", "包"), p("は"), r("大きくない", "おおきくない", "不大"), p("です。")), meaning: "这个包不大。" },
      ],
    },
    {
      id: "u7-g3",
      title: "な形容词肯定句",
      structure: jp(r("名詞", "めいし", "名词"), p("は な形容词 です")),
      explanation: "な形容词作谓语时，也可直接接「です」。",
      usage: "「静か」「便利」「きれい」在本课按な形容词学习。",
      examples: [
        { japanese: jp(r("図書館", "としょかん", "图书馆"), p("は"), r("静か", "しずか", "安静"), p("です。")), meaning: "图书馆很安静。" },
        { japanese: jp(r("駅", "えき", "车站"), p("は"), r("便利", "べんり", "方便"), p("です。")), meaning: "车站很方便。" },
      ],
    },
    {
      id: "u7-g4",
      title: "な形容词否定句",
      structure: jp(r("静か", "しずか", "安静"), p("ではありません")),
      explanation: "な形容词的礼貌否定常用「ではありません」。",
      usage: "口语中也会听到「じゃありません」，本课先掌握书面礼貌形式。",
      examples: [
        { japanese: jp(r("ここ", "ここ", "这里"), p("は"), r("静か", "しずか", "安静"), p("ではありません。")), meaning: "这里不安静。" },
        { japanese: jp(r("この", "この", "这个"), r("店", "みせ", "商店"), p("は"), r("便利", "べんり", "方便"), p("ではありません。")), meaning: "这家店不方便。" },
      ],
    },
  ],
  examples: [
    { japanese: jp(r("この", "この", "这个"), r("教室", "きょうしつ", "教室"), p("は"), r("大きい", "おおきい", "大的"), p("です。")), meaning: "这间教室很大。" },
    { japanese: jp(r("この", "この", "这个"), r("時計", "とけい", "钟；表"), p("は"), r("古い", "ふるい", "旧的"), p("です。")), meaning: "这块表很旧。" },
    { japanese: jp(p("このコーヒーは"), r("高くない", "たかくない", "不贵"), p("です。")), meaning: "这杯咖啡不贵。" },
    { japanese: jp(r("図書館", "としょかん", "图书馆"), p("は"), r("静か", "しずか", "安静"), p("です。")), meaning: "图书馆很安静。" },
    { japanese: jp(r("駅", "えき", "车站"), p("の"), r("近く", "ちかく", "附近"), p("は"), r("便利", "べんり", "方便"), p("です。")), meaning: "车站附近很方便。" },
    { japanese: jp(r("ここ", "ここ", "这里"), p("は"), r("静か", "しずか", "安静"), p("ではありません。")), meaning: "这里不安静。" },
  ],
  reading: {
    title: "新开的咖啡店",
    intro: "两位同学聊新开的咖啡店和学习地点。",
    lines: [
      {
        speaker: "葵",
        japanese: jp(r("駅", "えき", "车站"), p("の"), r("近く", "ちかく", "附近"), p("に"), r("新しい", "あたらしい", "新的"), p("カフェがあります。")),
        meaning: "车站附近有一家新咖啡店。",
        keywords: [{ term: "新しい", reading: "あたらしい", meaning: "新的" }],
      },
      {
        speaker: "陳",
        japanese: jp(p("そこは"), r("静か", "しずか", "安静"), p("ですか。")),
        meaning: "那里安静吗？",
        keywords: [{ term: "静か", reading: "しずか", meaning: "安静" }],
      },
      {
        speaker: "葵",
        japanese: jp(p("はい、とても"), r("静か", "しずか", "安静"), p("です。コーヒーもおいしいです。")),
        meaning: "是的，非常安静。咖啡也好喝。",
        keywords: [{ term: "とても", reading: "とても", meaning: "非常" }],
      },
      {
        speaker: "陳",
        japanese: jp(r("値段", "ねだん", "价格"), p("は"), r("高い", "たかい", "贵的"), p("ですか。")),
        meaning: "价格贵吗？",
        keywords: [{ term: "値段", reading: "ねだん", meaning: "价格" }],
      },
      {
        speaker: "葵",
        japanese: jp(p("いいえ、"), r("高くない", "たかくない", "不贵"), p("です。")),
        meaning: "不，不贵。",
        keywords: [{ term: "高くない", reading: "たかくない", meaning: "不贵" }],
      },
    ],
  },
  exercises: [
    {
      id: "u7-e1",
      type: "multiple-choice",
      prompt: jp(p("哪个词是い形容词？")),
      options: [jp(r("大きい", "おおきい", "大的")), jp(r("静か", "しずか", "安静")), "きれい", jp(r("便利", "べんり", "方便"))],
      correctAnswer: jp(r("大きい", "おおきい", "大的")),
      explanation: jp(r("大きい", "おおきい", "大的"), p("以い结尾，是い形容词。")),
    },
    {
      id: "u7-e2",
      type: "fill-blank",
      prompt: jp(r("この", "この", "这个"), r("本", "ほん", "书"), p("は"), r("新しい", "あたらしい", "新的"), p(" ____。")),
      correctAnswer: "です",
      explanation: jp(p("形容词肯定句可用「形容词 + です」。")),
    },
    {
      id: "u7-e3",
      type: "order-sentence",
      prompt: jp(p("排列成“图书馆很安静”。")),
      parts: [r("図書館", "としょかん", "图书馆"), r("静か", "しずか", "安静"), p("です"), p("は")],
      correctOrder: [r("図書館", "としょかん", "图书馆"), p("は"), r("静か", "しずか", "安静"), p("です")],
      explanation: jp(p("な形容词作谓语时，可以直接接「です」。")),
    },
    {
      id: "u7-e4",
      type: "true-false",
      prompt: jp(p("判断否定形式。")),
      statement: jp(r("高い", "たかい", "贵的"), p("的简单否定是"), r("高くない", "たかくない", "不贵"), p("です。")),
      correctAnswer: true,
      explanation: jp(p("い形容词否定通常把「い」变为「くない」。")),
    },
    {
      id: "u7-e5",
      type: "matching",
      prompt: jp(p("匹配形容词和中文意思。")),
      pairs: [
        { left: jp(r("古い", "ふるい", "旧的")), right: "旧的" },
        { left: jp(r("安い", "やすい", "便宜的")), right: "便宜的" },
        { left: jp(r("便利", "べんり", "方便")), right: "方便" },
        { left: jp(r("静か", "しずか", "安静")), right: "安静" },
      ],
      explanation: jp(p("这些词都可以用来描述人、物或地点。")),
    },
    {
      id: "u7-e6",
      type: "multiple-choice",
      prompt: jp(p("哪一句表示“这里不安静”？")),
      options: [
        jp(r("ここ", "ここ", "这里"), p("は"), r("静か", "しずか", "安静"), p("ではありません。")),
        jp(r("ここ", "ここ", "这里"), p("は"), r("静か", "しずか", "安静"), p("です。")),
        jp(r("ここ", "ここ", "这里"), p("は"), r("大きい", "おおきい", "大的"), p("です。")),
        jp(r("ここ", "ここ", "这里"), p("は"), r("高くない", "たかくない", "不贵"), p("です。")),
      ],
      correctAnswer: jp(r("ここ", "ここ", "这里"), p("は"), r("静か", "しずか", "安静"), p("ではありません。")),
      explanation: jp(r("静か", "しずか", "安静"), p("的礼貌否定是「静かではありません」。")),
    },
    {
      id: "u7-e7",
      type: "fill-blank",
      prompt: jp(p("このコーヒーは"), r("高くない", "たかくない", "不贵"), p(" ____。")),
      correctAnswer: "です",
      explanation: jp(r("高くない", "たかくない", "不贵"), p("后接「です」构成礼貌句。")),
    },
    {
      id: "u7-e8",
      type: "true-false",
      prompt: jp(p("判断词类。")),
      statement: jp(r("便利", "べんり", "方便"), p("在本课按な形容词学习。")),
      correctAnswer: true,
      explanation: jp(r("便利", "べんり", "方便"), p("作谓语时可说「便利です」。")),
    },
    {
      id: "u7-e9",
      type: "order-sentence",
      prompt: jp(p("排列成“这个包不大”。")),
      parts: [r("この", "この", "这个"), r("鞄", "かばん", "包"), p("は"), r("大きくない", "おおきくない", "不大"), p("です")],
      correctOrder: [r("この", "この", "这个"), r("鞄", "かばん", "包"), p("は"), r("大きくない", "おおきくない", "不大"), p("です")],
      explanation: jp(r("大きい", "おおきい", "大的"), p("的否定是"), r("大きくない", "おおきくない", "不大"), p("。")),
    },
    {
      id: "u7-e10",
      type: "multiple-choice",
      prompt: jp(p("哪一句表示“这个面包很好吃”？")),
      options: [
        jp(p("このパンはおいしいです。")),
        jp(p("このパンは"), r("便利", "べんり", "方便"), p("です。")),
        jp(p("このパンは"), r("古い", "ふるい", "旧的"), p("です。")),
        jp(p("このパンは"), r("静か", "しずか", "安静"), p("です。")),
      ],
      correctAnswer: jp(r("昼ご飯", "ひるごはん", "午饭"), p("はおいしいです。")),
      explanation: jp(p("食物好吃可以说「おいしいです」。")),
    },
  ],
};
