import type { Lesson } from "../types";

export const unit4: Lesson = {
  id: "unit-4",
  unit: 4,
  title: "时间表达",
  subtitle: "安排一天，也约定下一次见面",
  description:
    "学习整点、分钟和常用时间段，用「から・まで」表达起止，并询问活动在几点开始。",
  duration: "约 45 分钟",
  accent: "#8a6b98",
  goals: [
    "准确读出常见整点和分钟",
    "用「何時ですか」询问时间",
    "用「から・まで」说明时间范围",
    "用「ごろ」表达大约时间",
  ],
  vocabulary: [
    {
      id: "u4-w1",
      japanese: "今",
      kana: "いま",
      meaning: "现在",
      partOfSpeech: "名词／副词",
      example: "今、九時半です。",
      exampleMeaning: "现在九点半。",
    },
    {
      id: "u4-w2",
      japanese: "午前",
      kana: "ごぜん",
      meaning: "上午；午前",
      partOfSpeech: "名词",
      example: "授業は午前十時からです。",
      exampleMeaning: "课从上午十点开始。",
    },
    {
      id: "u4-w3",
      japanese: "午後",
      kana: "ごご",
      meaning: "下午；午后",
      partOfSpeech: "名词",
      example: "午後は図書館にいます。",
      exampleMeaning: "下午我在图书馆。",
    },
    {
      id: "u4-w4",
      japanese: "半",
      kana: "はん",
      meaning: "半；半点",
      partOfSpeech: "名词／接尾词",
      example: "会議は一時半です。",
      exampleMeaning: "会议一点半开始。",
    },
    {
      id: "u4-w5",
      japanese: "朝",
      kana: "あさ",
      meaning: "早晨",
      partOfSpeech: "名词",
      example: "朝は七時に起きます。",
      exampleMeaning: "早上七点起床。",
    },
    {
      id: "u4-w6",
      japanese: "昼",
      kana: "ひる",
      meaning: "白天；中午",
      partOfSpeech: "名词",
      example: "昼の十二時に休みます。",
      exampleMeaning: "中午十二点休息。",
    },
    {
      id: "u4-w7",
      japanese: "夜",
      kana: "よる",
      meaning: "夜晚",
      partOfSpeech: "名词",
      example: "夜は本を読みます。",
      exampleMeaning: "晚上读书。",
    },
    {
      id: "u4-w8",
      japanese: "授業",
      kana: "じゅぎょう",
      meaning: "课；课程",
      partOfSpeech: "名词",
      example: "今日の授業は三時までです。",
      exampleMeaning: "今天的课到三点结束。",
    },
    {
      id: "u4-w9",
      japanese: "休み",
      kana: "やすみ",
      meaning: "休息；休假",
      partOfSpeech: "名词",
      example: "昼休みは一時間です。",
      exampleMeaning: "午休是一小时。",
    },
    {
      id: "u4-w10",
      japanese: "約束",
      kana: "やくそく",
      meaning: "约定",
      partOfSpeech: "名词",
      example: "土曜日に友達と約束があります。",
      exampleMeaning: "周六和朋友有约。",
    },
  ],
  grammar: [
    {
      id: "u4-g1",
      title: "整点表达",
      structure: "数字 + 時（じ）",
      explanation:
        "时间的“点”用「時」。四点读「よじ」、七点读「しちじ」、九点读「くじ」，需要特别记忆。",
      usage:
        "上午和下午分别放在时间前，如「午前九時」「午後三時」。",
      examples: [
        { japanese: "今、午前九時です。", meaning: "现在是上午九点。" },
        { japanese: "店は午後七時までです。", meaning: "店营业到晚上七点。" },
      ],
    },
    {
      id: "u4-g2",
      title: "分钟与半点",
      structure: "数字 + 分（ふん／ぷん） / 時半",
      explanation:
        "「分」会因前面的数字发生读音变化，如一分 ippun、三分 sanpun、五分 gofun。半点可直接说「半」。",
      usage:
        "例如「九時三十分」与「九時半」都表示九点半。",
      examples: [
        { japanese: "八時十五分です。", meaning: "八点十五分。" },
        { japanese: "十時半に始まります。", meaning: "十点半开始。" },
        { japanese: "あと五分です。", meaning: "还有五分钟。" },
      ],
    },
    {
      id: "u4-g3",
      title: "询问时间",
      structure: "何時ですか / 何時からですか",
      explanation:
        "「何時」读作 nanji，用于询问具体时间。结合「から」可以询问开始时间。",
      usage:
        "询问现在时间可说「今、何時ですか」，询问课程可说「授業は何時からですか」。",
      examples: [
        { japanese: "今、何時ですか。", meaning: "现在几点？" },
        { japanese: "映画は何時からですか。", meaning: "电影几点开始？" },
      ],
    },
    {
      id: "u4-g4",
      title: "起止与大约时间",
      structure: "A から B まで / 時間 + ごろ",
      explanation:
        "「から」表示起点，“从……起”；「まで」表示终点，“到……为止”。「ごろ」表示大约的时间点。",
      usage:
        "「から」和「まで」可以单独使用。时间点后加「ごろ」时通常不再加「に」。",
      examples: [
        { japanese: "授業は九時から十二時までです。", meaning: "课从九点到十二点。" },
        { japanese: "七時ごろ起きます。", meaning: "七点左右起床。" },
        { japanese: "仕事は六時までです。", meaning: "工作到六点结束。" },
      ],
    },
  ],
  examples: [
    { japanese: "今、何時ですか。", meaning: "现在几点？" },
    { japanese: "午前八時十五分です。", meaning: "上午八点十五分。" },
    { japanese: "会議は午後二時半からです。", meaning: "会议从下午两点半开始。" },
    { japanese: "図書館は九時から六時までです。", meaning: "图书馆从九点开放到六点。" },
    { japanese: "私は七時ごろ起きます。", meaning: "我七点左右起床。" },
    { japanese: "昼休みは十二時からです。", meaning: "午休从十二点开始。" },
  ],
  reading: {
    title: "土曜日の予定",
    intro: "两位朋友在聊天中安排周六一起学习和吃饭的时间。",
    lines: [
      {
        speaker: "葵",
        japanese: "土曜日、いっしょに日本語を勉強しませんか。",
        meaning: "周六要不要一起学日语？",
        keywords: [
          { term: "土曜日", reading: "どようび", meaning: "星期六" },
          { term: "勉強", reading: "べんきょう", meaning: "学习" },
        ],
      },
      {
        speaker: "陳",
        japanese: "いいですね。何時からですか。",
        meaning: "好啊。几点开始？",
        keywords: [{ term: "何時", reading: "なんじ", meaning: "几点" }],
      },
      {
        speaker: "葵",
        japanese: "午前十時ごろはどうですか。",
        meaning: "上午十点左右怎么样？",
        keywords: [{ term: "ごろ", reading: "ごろ", meaning: "大约；左右" }],
      },
      {
        speaker: "陳",
        japanese: "十時半なら大丈夫です。",
        meaning: "十点半的话没问题。",
        keywords: [
          { term: "なら", reading: "なら", meaning: "如果是……的话" },
          { term: "大丈夫", reading: "だいじょうぶ", meaning: "没问题" },
        ],
      },
      {
        speaker: "葵",
        japanese: "では、十時半から十二時まで勉強しましょう。",
        meaning: "那么，我们从十点半学到十二点吧。",
        keywords: [{ term: "まで", reading: "まで", meaning: "到……为止" }],
      },
      {
        speaker: "陳",
        japanese: "はい。そのあと、駅の近くで昼ご飯を食べましょう。",
        meaning: "好。之后在车站附近吃午饭吧。",
        keywords: [
          { term: "そのあと", reading: "そのあと", meaning: "之后" },
          { term: "昼ご飯", reading: "ひるごはん", meaning: "午饭" },
        ],
      },
    ],
  },
  exercises: [
    {
      id: "u4-e1",
      type: "multiple-choice",
      prompt: "「九時半」表示几点？",
      options: ["9:00", "9:15", "9:30", "9:45"],
      correctAnswer: "9:30",
      explanation: "时间后的「半」表示半小时，即 30 分钟。",
    },
    {
      id: "u4-e2",
      type: "fill-blank",
      prompt: "补全问题：今、____ ですか。（现在几点？）",
      correctAnswer: "何時",
      acceptedAnswers: ["なんじ"],
      explanation: "「何時」读作「なんじ」，用于询问几点。",
    },
    {
      id: "u4-e3",
      type: "order-sentence",
      prompt: "排列成“课从九点开始”。",
      parts: ["九時", "授業", "です", "から", "は"],
      correctOrder: ["授業", "は", "九時", "から", "です"],
      explanation: "「から」接在起始时间之后。",
    },
    {
      id: "u4-e4",
      type: "true-false",
      prompt: "判断时间读法。",
      statement: "日语的“四点”通常读作「よじ」。",
      correctAnswer: true,
      explanation: "四点读「よじ」，不是「よんじ」。",
    },
    {
      id: "u4-e5",
      type: "matching",
      prompt: "匹配时间表达。",
      pairs: [
        { left: "午前七時", right: "上午 7:00" },
        { left: "午後三時", right: "下午 3:00" },
        { left: "八時半", right: "8:30" },
        { left: "十時十五分", right: "10:15" },
      ],
      explanation: "「午前」对应上午，「午後」对应下午，「半」表示 30 分钟。",
    },
    {
      id: "u4-e6",
      type: "multiple-choice",
      prompt: "“图书馆从九点开放到六点”中，“到”用哪个助词？",
      options: ["から", "まで", "ごろ", "の"],
      correctAnswer: "まで",
      explanation: "「まで」表示终点；「から」表示起点。",
    },
    {
      id: "u4-e7",
      type: "fill-blank",
      prompt: "补全句子：七時 ____ 起きます。（七点左右起床）",
      correctAnswer: "ごろ",
      explanation: "时间点后接「ごろ」表示大约、左右。",
    },
    {
      id: "u4-e8",
      type: "true-false",
      prompt: "判断句意。",
      statement: "「授業は三時までです」表示课程三点开始。",
      correctAnswer: false,
      explanation: "「まで」表示终点，所以句意是“课程到三点结束”。",
    },
    {
      id: "u4-e9",
      type: "order-sentence",
      prompt: "排列成“会议从下午两点半开始”。",
      parts: ["午後二時半", "会議", "から", "です", "は"],
      correctOrder: ["会議", "は", "午後二時半", "から", "です"],
      explanation: "起始时间「午後二時半」后接「から」。",
    },
    {
      id: "u4-e10",
      type: "multiple-choice",
      prompt: "询问电影几点开始，哪一句最合适？",
      options: [
        "映画は何時からですか。",
        "映画はどこからですか。",
        "映画は何ですか。",
        "何時は映画ですか。",
      ],
      correctAnswer: "映画は何時からですか。",
      explanation: "「何時からですか」询问开始时间。",
    },
  ],
};
