import type { Lesson } from "../types";
import { jp, p, r } from "./text";

export const unit14: Lesson = {
  id: "unit-14",
  unit: 14,
  title: "日期、星期与日程",
  subtitle: "说今天、明天、星期几和简单安排",
  description:
    "学习日期、星期和基础日程表达，用「に」「があります」说明什么时候有什么安排。",
  duration: "约 50 分钟",
  accent: "#6aa36f",
  goals: [
    "掌握今天、明天、昨天等时间词",
    "用星期和月日说明日程",
    "用「予定があります」表达有安排",
  ],
  vocabulary: [
    { id: "u14-w1", japanese: jp(r("今日", "きょう", "今天")), kana: "きょう", meaning: "今天", partOfSpeech: "名词", example: jp(r("今日", "きょう", "今天"), p("は"), r("月曜日", "げつようび", "星期一"), p("です。")), exampleMeaning: "今天是星期一。" },
    { id: "u14-w2", japanese: jp(r("明日", "あした", "明天")), kana: "あした", meaning: "明天", partOfSpeech: "名词", example: jp(r("明日", "あした", "明天"), p("、"), r("授業", "じゅぎょう", "课"), p("があります。")), exampleMeaning: "明天有课。" },
    { id: "u14-w3", japanese: jp(r("昨日", "きのう", "昨天")), kana: "きのう", meaning: "昨天", partOfSpeech: "名词", example: jp(r("昨日", "きのう", "昨天"), p("は"), r("日曜日", "にちようび", "星期日"), p("でした。")), exampleMeaning: "昨天是星期日。" },
    { id: "u14-w4", japanese: jp(r("今週", "こんしゅう", "这周")), kana: "こんしゅう", meaning: "这周", partOfSpeech: "名词", example: jp(r("今週", "こんしゅう", "这周"), p("は"), r("忙", "いそが", "忙"), p("しいです。")), exampleMeaning: "这周很忙。" },
    { id: "u14-w5", japanese: jp(r("来週", "らいしゅう", "下周")), kana: "らいしゅう", meaning: "下周", partOfSpeech: "名词", example: jp(r("来週", "らいしゅう", "下周"), p("、"), r("試験", "しけん", "考试"), p("があります。")), exampleMeaning: "下周有考试。" },
    { id: "u14-w6", japanese: jp(r("月曜日", "げつようび", "星期一")), kana: "げつようび", meaning: "星期一", partOfSpeech: "名词", example: jp(r("月曜日", "げつようび", "星期一"), p("に"), r("会議", "かいぎ", "会议"), p("があります。")), exampleMeaning: "星期一有会议。" },
    { id: "u14-w7", japanese: jp(r("火曜日", "かようび", "星期二")), kana: "かようび", meaning: "星期二", partOfSpeech: "名词", example: jp(r("火曜日", "かようび", "星期二"), p("に"), r("日本語", "にほんご", "日语"), p("を"), r("勉強", "べんきょう", "学习"), p("します。")), exampleMeaning: "星期二学日语。" },
    { id: "u14-w8", japanese: jp(r("水曜日", "すいようび", "星期三")), kana: "すいようび", meaning: "星期三", partOfSpeech: "名词", example: jp(r("水曜日", "すいようび", "星期三"), p("はひまです。")), exampleMeaning: "星期三有空。" },
    { id: "u14-w9", japanese: jp(r("木曜日", "もくようび", "星期四")), kana: "もくようび", meaning: "星期四", partOfSpeech: "名词", example: jp(r("木曜日", "もくようび", "星期四"), p("に"), r("映画", "えいが", "电影"), p("を"), r("見", "み", "看"), p("ます。")), exampleMeaning: "星期四看电影。" },
    { id: "u14-w10", japanese: jp(r("金曜日", "きんようび", "星期五")), kana: "きんようび", meaning: "星期五", partOfSpeech: "名词", example: jp(r("金曜日", "きんようび", "星期五"), p("に"), r("友達", "ともだち", "朋友"), p("と"), r("会", "あ", "见面"), p("います。")), exampleMeaning: "星期五和朋友见面。" },
    { id: "u14-w11", japanese: jp(r("予定", "よてい", "计划")), kana: "よてい", meaning: "计划；安排", partOfSpeech: "名词", example: jp(r("明日", "あした", "明天"), p("は"), r("予定", "よてい", "计划"), p("があります。")), exampleMeaning: "明天有安排。" },
    { id: "u14-w12", japanese: jp(r("誕生日", "たんじょうび", "生日")), kana: "たんじょうび", meaning: "生日", partOfSpeech: "名词", example: jp(r("六月", "ろくがつ", "六月"), p(""), r("十日", "とおか", "十日"), p("は"), r("誕生日", "たんじょうび", "生日"), p("です。")), exampleMeaning: "六月十日是生日。" },
  ],
  grammar: [
    {
      id: "u14-g1",
      title: "星期表达",
      structure: jp(r("今日", "きょう", "今天"), p("は"), r("月曜日", "げつようび", "星期一"), p("です")),
      explanation: "说明今天或某天是星期几，用「AはBです」。",
      usage: "昨天说过去时，用「でした」。",
      examples: [
        { japanese: jp(r("今日", "きょう", "今天"), p("は"), r("月曜日", "げつようび", "星期一"), p("です。")), meaning: "今天是星期一。" },
        { japanese: jp(r("昨日", "きのう", "昨天"), p("は"), r("日曜日", "にちようび", "星期日"), p("でした。")), meaning: "昨天是星期日。" },
      ],
    },
    {
      id: "u14-g2",
      title: "时间に",
      structure: jp(r("月曜日", "げつようび", "星期一"), p("に"), r("会議", "かいぎ", "会议"), p("があります")),
      explanation: "具体星期或日期后常接「に」，说明动作或安排发生的时间。",
      usage: "「今日」「明日」「昨日」后面通常不加「に」。",
      examples: [
        { japanese: jp(r("金曜日", "きんようび", "星期五"), p("に"), r("友達", "ともだち", "朋友"), p("と"), r("会", "あ", "见面"), p("います。")), meaning: "星期五和朋友见面。" },
        { japanese: jp(r("六月", "ろくがつ", "六月"), p(""), r("十日", "とおか", "十日"), p("に"), r("試験", "しけん", "考试"), p("があります。")), meaning: "六月十日有考试。" },
      ],
    },
    {
      id: "u14-g3",
      title: "予定があります",
      structure: jp(r("明日", "あした", "明天"), p("は"), r("予定", "よてい", "计划"), p("があります")),
      explanation: "「予定があります」表示有安排。",
      usage: "如果没有安排，可以说「予定がありません」。",
      examples: [
        { japanese: jp(r("明日", "あした", "明天"), p("は"), r("予定", "よてい", "计划"), p("があります。")), meaning: "明天有安排。" },
        { japanese: jp(r("水曜日", "すいようび", "星期三"), p("は"), r("予定", "よてい", "计划"), p("がありません。")), meaning: "星期三没有安排。" },
      ],
    },
  ],
  examples: [
    { japanese: jp(r("今日", "きょう", "今天"), p("は"), r("月曜日", "げつようび", "星期一"), p("です。")), meaning: "今天是星期一。" },
    { japanese: jp(r("明日", "あした", "明天"), p("、"), r("授業", "じゅぎょう", "课"), p("があります。")), meaning: "明天有课。" },
    { japanese: jp(r("来週", "らいしゅう", "下周"), p("、"), r("試験", "しけん", "考试"), p("があります。")), meaning: "下周有考试。" },
    { japanese: jp(r("金曜日", "きんようび", "星期五"), p("に"), r("友達", "ともだち", "朋友"), p("と"), r("会", "あ", "见面"), p("います。")), meaning: "星期五和朋友见面。" },
    { japanese: jp(r("六月", "ろくがつ", "六月"), p(""), r("十日", "とおか", "十日"), p("は"), r("誕生日", "たんじょうび", "生日"), p("です。")), meaning: "六月十日是生日。" },
    { japanese: jp(r("水曜日", "すいようび", "星期三"), p("は"), r("予定", "よてい", "计划"), p("がありません。")), meaning: "星期三没有安排。" },
  ],
  reading: {
    title: "来週の予定",
    intro: "两个人确认下周的简单日程。",
    lines: [
      {
        speaker: "王",
        japanese: jp(r("来週", "らいしゅう", "下周"), p("の"), r("予定", "よてい", "计划"), p("はどうですか。")),
        meaning: "下周的安排怎么样？",
        keywords: [{ term: "予定", reading: "よてい", meaning: "安排" }],
      },
      {
        speaker: "田中",
        japanese: jp(r("月曜日", "げつようび", "星期一"), p("に"), r("会議", "かいぎ", "会议"), p("があります。")),
        meaning: "星期一有会议。",
        keywords: [{ term: "月曜日", reading: "げつようび", meaning: "星期一" }],
      },
      {
        speaker: "王",
        japanese: jp(r("火曜日", "かようび", "星期二"), p("は？")),
        meaning: "星期二呢？",
        keywords: [],
      },
      {
        speaker: "田中",
        japanese: jp(r("火曜日", "かようび", "星期二"), p("は"), r("日本語", "にほんご", "日语"), p("の"), r("授業", "じゅぎょう", "课"), p("があります。")),
        meaning: "星期二有日语课。",
        keywords: [{ term: "授業", reading: "じゅぎょう", meaning: "课" }],
      },
      {
        speaker: "王",
        japanese: jp(r("金曜日", "きんようび", "星期五"), p("に"), r("映画", "えいが", "电影"), p("を"), r("見", "み", "看"), p("ませんか。")),
        meaning: "星期五看电影吗？",
        keywords: [{ term: "金曜日", reading: "きんようび", meaning: "星期五" }],
      },
      {
        speaker: "田中",
        japanese: jp(p("いいですね。"), r("金曜日", "きんようび", "星期五"), p("は"), r("予定", "よてい", "计划"), p("がありません。")),
        meaning: "好啊。星期五没有安排。",
        keywords: [{ term: "予定がありません", reading: "よていがありません", meaning: "没有安排" }],
      },
    ],
  },
  exercises: [
    { id: "u14-e1", type: "multiple-choice", prompt: jp(p("「明日」的读法是哪一个？")), options: ["あした", "きょう", "きのう", "らいしゅう"], correctAnswer: "あした", explanation: jp(r("明日", "あした", "明天"), p("读作 あした。")) },
    { id: "u14-e2", type: "fill-blank", prompt: jp(r("今日", "きょう", "今天"), p("は"), r("月曜日", "げつようび", "星期一"), p("____。")), correctAnswer: "です", explanation: jp(p("说明今天是星期几，用「です」。")) },
    { id: "u14-e3", type: "order-sentence", prompt: jp(p("排列成“星期一有会议”。")), parts: [r("月曜日", "げつようび", "星期一"), p("に"), r("会議", "かいぎ", "会议"), p("があります")], correctOrder: [r("月曜日", "げつようび", "星期一"), p("に"), r("会議", "かいぎ", "会议"), p("があります")], explanation: jp(p("具体星期后接「に」。")) },
    { id: "u14-e4", type: "true-false", prompt: jp(p("判断用法。")), statement: jp(r("明日", "あした", "明天"), p("は"), r("予定", "よてい", "计划"), p("があります。表示“明天有安排”。")), correctAnswer: true, explanation: jp(r("予定", "よてい", "计划"), p("があります 表示有安排。")) },
    { id: "u14-e5", type: "matching", prompt: jp(p("匹配星期。")), pairs: [{ left: jp(r("月曜日", "げつようび", "星期一")), right: "星期一" }, { left: jp(r("火曜日", "かようび", "星期二")), right: "星期二" }, { left: jp(r("水曜日", "すいようび", "星期三")), right: "星期三" }, { left: jp(r("金曜日", "きんようび", "星期五")), right: "星期五" }], explanation: jp(p("曜日表示星期。")) },
    { id: "u14-e6", type: "multiple-choice", prompt: jp(p("哪一句表示“下周有考试”？")), options: [jp(r("来週", "らいしゅう", "下周"), p("、"), r("試験", "しけん", "考试"), p("があります。")), jp(r("今週", "こんしゅう", "这周"), p("は"), r("試験", "しけん", "考试"), p("でした。")), jp(r("来週", "らいしゅう", "下周"), p("、"), r("映画", "えいが", "电影"), p("を"), r("見", "み", "看"), p("ました。")), jp(r("昨日", "きのう", "昨天"), p("、"), r("試験", "しけん", "考试"), p("があります。"))], correctAnswer: jp(r("来週", "らいしゅう", "下周"), p("、"), r("試験", "しけん", "考试"), p("があります。")), explanation: jp(r("来週", "らいしゅう", "下周"), p("表示下周。")) },
    { id: "u14-e7", type: "fill-blank", prompt: jp(r("金曜日", "きんようび", "星期五"), p("____"), r("友達", "ともだち", "朋友"), p("と"), r("会", "あ", "见面"), p("います。")), correctAnswer: "に", explanation: jp(p("具体星期后常接「に」。")) },
    { id: "u14-e8", type: "true-false", prompt: jp(p("判断句意。")), statement: jp(r("水曜日", "すいようび", "星期三"), p("は"), r("予定", "よてい", "计划"), p("がありません。表示“星期三没有安排”。")), correctAnswer: true, explanation: jp(r("予定", "よてい", "计划"), p("がありません 表示没有安排。")) },
    { id: "u14-e9", type: "order-sentence", prompt: jp(p("排列成“六月十日是生日”。")), parts: [r("六月", "ろくがつ", "六月"), r("十日", "とおか", "十日"), p("は"), r("誕生日", "たんじょうび", "生日"), p("です")], correctOrder: [r("六月", "ろくがつ", "六月"), r("十日", "とおか", "十日"), p("は"), r("誕生日", "たんじょうび", "生日"), p("です")], explanation: jp(p("月日后接主题助词「は」。")) },
    { id: "u14-e10", type: "multiple-choice", prompt: jp(p("「昨天是星期日」应该选择哪一句？")), options: [jp(r("昨日", "きのう", "昨天"), p("は"), r("日曜日", "にちようび", "星期日"), p("でした。")), jp(r("昨日", "きのう", "昨天"), p("は"), r("日曜日", "にちようび", "星期日"), p("です。")), jp(r("明日", "あした", "明天"), p("は"), r("日曜日", "にちようび", "星期日"), p("でした。")), jp(r("今日", "きょう", "今天"), p("は"), r("日曜日", "にちようび", "星期日"), p("でした。"))], correctAnswer: jp(r("昨日", "きのう", "昨天"), p("は"), r("日曜日", "にちようび", "星期日"), p("でした。")), explanation: jp(r("昨日", "きのう", "昨天"), p("是过去时间，句尾用「でした」。")) },
    { id: "u14-e11", type: "fill-blank", prompt: jp(r("明日", "あした", "明天"), p("、"), r("授業", "じゅぎょう", "课"), p("が____。")), correctAnswer: "あります", explanation: jp(r("授業", "じゅぎょう", "课"), p("があります 表示有课。")) },
    { id: "u14-e12", type: "matching", prompt: jp(p("匹配时间词。")), pairs: [{ left: jp(r("今日", "きょう", "今天")), right: "今天" }, { left: jp(r("明日", "あした", "明天")), right: "明天" }, { left: jp(r("昨日", "きのう", "昨天")), right: "昨天" }, { left: jp(r("来週", "らいしゅう", "下周")), right: "下周" }], explanation: jp(p("这些是常用时间词。")) },
  ],
};
