import type { Lesson } from "../types";

export const unit2: Lesson = {
  id: "unit-2",
  unit: 2,
  title: "これ・それ・あれ",
  subtitle: "在物品之间建立距离感",
  description:
    "学习指示物品的表达，询问物品名称和所属，并在真实场景中区分说话人与听话人的距离。",
  duration: "约 40 分钟",
  accent: "#b98935",
  goals: [
    "根据距离正确使用「これ・それ・あれ」",
    "用「何ですか」询问不认识的物品",
    "用「この・その・あの + 名词」修饰具体事物",
  ],
  vocabulary: [
    {
      id: "u2-w1",
      japanese: "本",
      kana: "ほん",
      meaning: "书",
      partOfSpeech: "名词",
      example: "これは写真の本です。",
      exampleMeaning: "这是一本摄影书。",
    },
    {
      id: "u2-w2",
      japanese: "辞書",
      kana: "じしょ",
      meaning: "词典",
      partOfSpeech: "名词",
      example: "その辞書は使いやすいです。",
      exampleMeaning: "那本词典很好用。",
    },
    {
      id: "u2-w3",
      japanese: "ノート",
      kana: "ノート",
      meaning: "笔记本",
      partOfSpeech: "名词",
      example: "青いノートは私のです。",
      exampleMeaning: "蓝色笔记本是我的。",
    },
    {
      id: "u2-w4",
      japanese: "傘",
      kana: "かさ",
      meaning: "伞",
      partOfSpeech: "名词",
      example: "これは軽い傘です。",
      exampleMeaning: "这是一把轻便的伞。",
    },
    {
      id: "u2-w5",
      japanese: "鍵",
      kana: "かぎ",
      meaning: "钥匙",
      partOfSpeech: "名词",
      example: "机の上に鍵があります。",
      exampleMeaning: "桌上有钥匙。",
    },
    {
      id: "u2-w6",
      japanese: "鞄",
      kana: "かばん",
      meaning: "包",
      partOfSpeech: "名词",
      example: "あの鞄は丈夫です。",
      exampleMeaning: "那个包很结实。",
    },
    {
      id: "u2-w7",
      japanese: "写真",
      kana: "しゃしん",
      meaning: "照片",
      partOfSpeech: "名词",
      example: "それは旅行の写真です。",
      exampleMeaning: "那是旅行时的照片。",
    },
    {
      id: "u2-w8",
      japanese: "時計",
      kana: "とけい",
      meaning: "钟；表",
      partOfSpeech: "名词",
      example: "この時計は祖父のです。",
      exampleMeaning: "这块表是祖父的。",
    },
    {
      id: "u2-w9",
      japanese: "誰",
      kana: "だれ",
      meaning: "谁",
      partOfSpeech: "疑问词",
      example: "これは誰の傘ですか。",
      exampleMeaning: "这是谁的伞？",
    },
    {
      id: "u2-w10",
      japanese: "何",
      kana: "なん／なに",
      meaning: "什么",
      partOfSpeech: "疑问词",
      example: "それは何ですか。",
      exampleMeaning: "那是什么？",
    },
  ],
  grammar: [
    {
      id: "u2-g1",
      title: "指示物品",
      structure: "これ / それ / あれ",
      explanation:
        "「これ」指靠近说话人的物品，「それ」指靠近听话人的物品，「あれ」指离双方都较远的物品。",
      usage:
        "这三个词可以直接作名词使用，后面不再接名词。",
      examples: [
        { japanese: "これは私のノートです。", meaning: "这是我的笔记本。" },
        { japanese: "それは何ですか。", meaning: "那是什么？" },
        { japanese: "あれは駅の時計です。", meaning: "那是车站的钟。" },
      ],
    },
    {
      id: "u2-g2",
      title: "修饰名词",
      structure: "この / その / あの + 名词",
      explanation:
        "「この・その・あの」表达的距离关系与「これ・それ・あれ」相同，但必须放在名词前。",
      usage:
        "不能只说「このです」，也不能说「これ本」。",
      examples: [
        { japanese: "この本はおもしろいです。", meaning: "这本书很有意思。" },
        { japanese: "その傘は誰のですか。", meaning: "那把伞是谁的？" },
        { japanese: "あの建物は図書館です。", meaning: "那栋建筑是图书馆。" },
      ],
    },
    {
      id: "u2-g3",
      title: "询问物品",
      structure: "これは何ですか",
      explanation:
        "疑问词「何」可替换判断句中的物品名称，用来询问“这是什么”。在「何ですか」中通常读作 nan。",
      usage:
        "回答时可用「これは〜です」，语境明确时也可直接说「〜です」。",
      examples: [
        { japanese: "これは何ですか。", meaning: "这是什么？" },
        { japanese: "旅行の地図です。", meaning: "是旅行地图。" },
      ],
    },
    {
      id: "u2-g4",
      title: "询问所属",
      structure: "誰の + 名词 / 誰のですか",
      explanation:
        "「誰の」用于询问所属。已知物品名称时，也可以省略名词，说「誰のですか」。",
      usage:
        "回答可使用「私のです」「木村さんの鞄です」等。",
      examples: [
        { japanese: "これは誰の鍵ですか。", meaning: "这是谁的钥匙？" },
        { japanese: "そのノートは誰のですか。", meaning: "那本笔记本是谁的？" },
        { japanese: "私のです。", meaning: "是我的。" },
      ],
    },
  ],
  examples: [
    { japanese: "これは新しい辞書です。", meaning: "这是一本新词典。" },
    { japanese: "それは何ですか。", meaning: "那是什么？" },
    { japanese: "あれは駅の案内板です。", meaning: "那是车站的指示牌。" },
    { japanese: "この写真は京都の写真です。", meaning: "这张照片是在京都拍的。" },
    { japanese: "その鍵は誰のですか。", meaning: "那把钥匙是谁的？" },
    { japanese: "あの鞄は私のではありません。", meaning: "那个包不是我的。" },
  ],
  reading: {
    title: "忘れ物コーナー",
    intro: "咖啡店的失物招领处，店员帮助客人确认遗失的物品。",
    lines: [
      {
        speaker: "客",
        japanese: "すみません。これは忘れ物ですか。",
        meaning: "不好意思。这是遗失物品吗？",
        keywords: [{ term: "忘れ物", reading: "わすれもの", meaning: "遗失物品" }],
      },
      {
        speaker: "店員",
        japanese: "はい、今日の忘れ物です。",
        meaning: "是的，是今天的遗失物品。",
        keywords: [{ term: "今日", reading: "きょう", meaning: "今天" }],
      },
      {
        speaker: "客",
        japanese: "その青い傘は私のです。",
        meaning: "那把蓝色的伞是我的。",
        keywords: [{ term: "青い", reading: "あおい", meaning: "蓝色的" }],
      },
      {
        speaker: "店員",
        japanese: "では、この小さい鍵は誰のですか。",
        meaning: "那么，这把小钥匙是谁的呢？",
        keywords: [{ term: "小さい", reading: "ちいさい", meaning: "小的" }],
      },
      {
        speaker: "客",
        japanese: "それは私のではありません。",
        meaning: "那个不是我的。",
        keywords: [{ term: "ではありません", reading: "ではありません", meaning: "不是" }],
      },
    ],
  },
  exercises: [
    {
      id: "u2-e1",
      type: "multiple-choice",
      prompt: "说话人指着自己手里的书，应说哪一句？",
      options: ["これは本です。", "それは本です。", "あれは本です。", "このは本です。"],
      correctAnswer: "これは本です。",
      explanation: "靠近说话人的物品用「これ」。",
    },
    {
      id: "u2-e2",
      type: "fill-blank",
      prompt: "补全句子：____ 辞書は私のです。（说话人手边的词典）",
      correctAnswer: "この",
      explanation: "后面有名词「辞書」，因此使用「この」。",
    },
    {
      id: "u2-e3",
      type: "true-false",
      prompt: "判断用法。",
      statement: "「これ本です」是自然、完整的日语表达。",
      correctAnswer: false,
      explanation: "「これ」不能直接修饰名词。可说「これは本です」或「この本です」。",
    },
    {
      id: "u2-e4",
      type: "order-sentence",
      prompt: "排列成“那把伞是谁的？”",
      parts: ["ですか", "誰", "その傘", "の", "は"],
      correctOrder: ["その傘", "は", "誰", "の", "ですか"],
      explanation: "结构为「その傘は + 誰の + ですか」。",
    },
    {
      id: "u2-e5",
      type: "matching",
      prompt: "匹配距离与表达。",
      pairs: [
        { left: "靠近说话人", right: "これ" },
        { left: "靠近听话人", right: "それ" },
        { left: "离双方都较远", right: "あれ" },
      ],
      explanation: "こ-、そ-、あ-构成日语指示词的基本距离体系。",
    },
    {
      id: "u2-e6",
      type: "multiple-choice",
      prompt: "想问“这是什么”，哪一句正确？",
      options: ["これは何ですか。", "このは何ですか。", "これの何ですか。", "何はこれですか。"],
      correctAnswer: "これは何ですか。",
      explanation: "用「これ」作主题，以「何ですか」询问物品名称。",
    },
    {
      id: "u2-e7",
      type: "fill-blank",
      prompt: "补全回答：A：そのノートは誰のですか。B：私 ____ です。",
      correctAnswer: "の",
      explanation: "「私のです」意为“是我的”，省略了已知的名词「ノート」。",
    },
    {
      id: "u2-e8",
      type: "multiple-choice",
      prompt: "双方都离远处的钟较远，应如何指示？",
      options: ["この時計", "その時計", "あの時計", "これ時計"],
      correctAnswer: "あの時計",
      explanation: "离说话人与听话人都较远的具体名词前使用「あの」。",
    },
    {
      id: "u2-e9",
      type: "true-false",
      prompt: "判断句意。",
      statement: "「それは私のではありません」表示“那个不是我的”。",
      correctAnswer: true,
      explanation: "「私の」表示“我的（东西）”，“ではありません”表示否定。",
    },
    {
      id: "u2-e10",
      type: "order-sentence",
      prompt: "排列成“这张照片是旅行时的照片”。",
      parts: ["旅行", "この写真", "です", "の写真", "は"],
      correctOrder: ["この写真", "は", "旅行", "の写真", "です"],
      explanation: "「旅行の写真」表示旅行时拍摄的照片。",
    },
  ],
};
