import type { Lesson } from "../types";
import { jp, p, r } from "./text";

export const unit8: Lesson = {
  id: "unit-8",
  unit: 8,
  title: "喜好与擅长表达",
  subtitle: "说出喜好和擅长的事",
  description:
    "学习用「が」连接喜好和能力评价，表达喜欢、不喜欢、擅长和不擅长。",
  duration: "约 45 分钟",
  accent: "#be7190",
  goals: [
    "用「A が好きです」表达喜欢",
    "用「A が嫌いです」表达不喜欢",
    "用「A が上手です / 下手です」表达擅长和不擅长",
  ],
  vocabulary: [
    {
      id: "u8-w1",
      japanese: jp(r("好き", "すき", "喜欢")),
      kana: "すき",
      meaning: "喜欢",
      partOfSpeech: "な形容词",
      example: jp(r("音楽", "おんがく", "音乐"), p("が"), r("好き", "すき", "喜欢"), p("です。")),
      exampleMeaning: "喜欢音乐。",
    },
    {
      id: "u8-w2",
      japanese: jp(r("嫌い", "きらい", "讨厌；不喜欢")),
      kana: "きらい",
      meaning: "讨厌；不喜欢",
      partOfSpeech: "な形容词",
      example: jp(r("朝", "あさ", "早晨"), p("の"), r("電車", "でんしゃ", "电车"), p("が"), r("嫌い", "きらい", "不喜欢"), p("です。")),
      exampleMeaning: "不喜欢早上的电车。",
    },
    {
      id: "u8-w3",
      japanese: jp(r("上手", "じょうず", "擅长")),
      kana: "じょうず",
      meaning: "擅长",
      partOfSpeech: "な形容词",
      example: jp(r("山田", "やまだ", "山田"), p("さんは"), r("料理", "りょうり", "料理"), p("が"), r("上手", "じょうず", "擅长"), p("です。")),
      exampleMeaning: "山田很会做饭。",
    },
    {
      id: "u8-w4",
      japanese: jp(r("下手", "へた", "不擅长")),
      kana: "へた",
      meaning: "不擅长",
      partOfSpeech: "な形容词",
      example: jp(p("わたしは"), r("歌", "うた", "歌"), p("が"), r("下手", "へた", "不擅长"), p("です。")),
      exampleMeaning: "我不擅长唱歌。",
    },
    {
      id: "u8-w5",
      japanese: jp(r("料理", "りょうり", "料理")),
      kana: "りょうり",
      meaning: "料理；做饭",
      partOfSpeech: "名词",
      example: jp(r("料理", "りょうり", "料理"), p("が"), r("好き", "すき", "喜欢"), p("です。")),
      exampleMeaning: "喜欢做饭。",
    },
    {
      id: "u8-w6",
      japanese: jp(r("歌", "うた", "歌")),
      kana: "うた",
      meaning: "歌",
      partOfSpeech: "名词",
      example: jp(r("歌", "うた", "歌"), p("を"), r("聞きます", "ききます", "听"), p("。")),
      exampleMeaning: "听歌。",
    },
    {
      id: "u8-w7",
      japanese: jp(r("スポーツ", "スポーツ", "运动")),
      kana: "スポーツ",
      meaning: "运动",
      partOfSpeech: "名词",
      example: jp(r("兄", "あに", "哥哥"), p("はスポーツが"), r("好き", "すき", "喜欢"), p("です。")),
      exampleMeaning: "哥哥喜欢运动。",
    },
    {
      id: "u8-w8",
      japanese: jp(r("絵", "え", "画")),
      kana: "え",
      meaning: "画；图画",
      partOfSpeech: "名词",
      example: jp(r("妹", "いもうと", "妹妹"), p("は"), r("絵", "え", "画"), p("が"), r("上手", "じょうず", "擅长"), p("です。")),
      exampleMeaning: "妹妹画画很好。",
    },
    {
      id: "u8-w9",
      japanese: jp(r("野菜", "やさい", "蔬菜")),
      kana: "やさい",
      meaning: "蔬菜",
      partOfSpeech: "名词",
      example: jp(r("野菜", "やさい", "蔬菜"), p("が"), r("嫌い", "きらい", "不喜欢"), p("ではありません。")),
      exampleMeaning: "并不讨厌蔬菜。",
    },
    {
      id: "u8-w10",
      japanese: jp(r("練習", "れんしゅう", "练习")),
      kana: "れんしゅう",
      meaning: "练习",
      partOfSpeech: "名词",
      example: jp(r("毎日", "まいにち", "每天"), r("練習", "れんしゅう", "练习"), p("します。")),
      exampleMeaning: "每天练习。",
    },
  ],
  grammar: [
    {
      id: "u8-g1",
      title: "表达喜欢",
      structure: jp(r("名詞", "めいし", "名词"), p("が"), r("好き", "すき", "喜欢"), p("です")),
      explanation: "表示喜欢某物或某事时，用「が」标记喜欢的对象。",
      usage: "「好き」是な形容词，不是动词。",
      examples: [
        { japanese: jp(r("音楽", "おんがく", "音乐"), p("が"), r("好き", "すき", "喜欢"), p("です。")), meaning: "喜欢音乐。" },
        { japanese: jp(r("料理", "りょうり", "料理"), p("が"), r("好き", "すき", "喜欢"), p("です。")), meaning: "喜欢做饭。" },
      ],
    },
    {
      id: "u8-g2",
      title: "表达不喜欢",
      structure: jp(r("名詞", "めいし", "名词"), p("が"), r("嫌い", "きらい", "不喜欢"), p("です")),
      explanation: "「嫌い」表示不喜欢或讨厌。语气较直接，实际交流中可以委婉一些。",
      usage: "本课只学习句型，不用于评价别人。",
      examples: [
        { japanese: jp(r("朝", "あさ", "早晨"), p("の"), r("電車", "でんしゃ", "电车"), p("が"), r("嫌い", "きらい", "不喜欢"), p("です。")), meaning: "不喜欢早上的电车。" },
        { japanese: jp(r("野菜", "やさい", "蔬菜"), p("が"), r("嫌い", "きらい", "不喜欢"), p("ではありません。")), meaning: "并不讨厌蔬菜。" },
      ],
    },
    {
      id: "u8-g3",
      title: "表达擅长",
      structure: jp(r("名詞", "めいし", "名词"), p("が"), r("上手", "じょうず", "擅长"), p("です")),
      explanation: "「上手」表示某人做某事做得好，常用于评价别人。",
      usage: "直接说自己「上手です」有时显得自夸，本课主要用于第三人称。",
      examples: [
        { japanese: jp(r("田中", "たなか", "田中"), p("さんは"), r("日本語", "にほんご", "日语"), p("が"), r("上手", "じょうず", "擅长"), p("です。")), meaning: "田中日语很好。" },
        { japanese: jp(r("妹", "いもうと", "妹妹"), p("は"), r("絵", "え", "画"), p("が"), r("上手", "じょうず", "擅长"), p("です。")), meaning: "妹妹画画很好。" },
      ],
    },
    {
      id: "u8-g4",
      title: "表达不擅长",
      structure: jp(r("名詞", "めいし", "名词"), p("が"), r("下手", "へた", "不擅长"), p("です")),
      explanation: "「下手」表示不擅长。谈自己时可自然使用。",
      usage: "想表达更委婉时，也可说「上手ではありません」。",
      examples: [
        { japanese: jp(p("わたしは"), r("歌", "うた", "歌"), p("が"), r("下手", "へた", "不擅长"), p("です。")), meaning: "我不擅长唱歌。" },
        { japanese: jp(r("料理", "りょうり", "料理"), p("が"), r("上手", "じょうず", "擅长"), p("ではありません。")), meaning: "做饭不算擅长。" },
      ],
    },
  ],
  examples: [
    { japanese: jp(r("音楽", "おんがく", "音乐"), p("が"), r("好き", "すき", "喜欢"), p("です。")), meaning: "喜欢音乐。" },
    { japanese: jp(r("野菜", "やさい", "蔬菜"), p("が"), r("嫌い", "きらい", "不喜欢"), p("ではありません。")), meaning: "并不讨厌蔬菜。" },
    { japanese: jp(r("山田", "やまだ", "山田"), p("さんは"), r("料理", "りょうり", "料理"), p("が"), r("上手", "じょうず", "擅长"), p("です。")), meaning: "山田很会做饭。" },
    { japanese: jp(p("わたしは"), r("歌", "うた", "歌"), p("が"), r("下手", "へた", "不擅长"), p("です。")), meaning: "我不擅长唱歌。" },
    { japanese: jp(r("妹", "いもうと", "妹妹"), p("は"), r("絵", "え", "画"), p("が"), r("上手", "じょうず", "擅长"), p("です。")), meaning: "妹妹画画很好。" },
    { japanese: jp(r("兄", "あに", "哥哥"), p("はスポーツが"), r("好き", "すき", "喜欢"), p("です。")), meaning: "哥哥喜欢运动。" },
  ],
  reading: {
    title: "兴趣小聊",
    intro: "几位同学聊自己喜欢的事情和不太擅长的事情。",
    lines: [
      {
        speaker: "美咲",
        japanese: jp(r("陳", "ちん", "陈"), p("さんは"), r("音楽", "おんがく", "音乐"), p("が"), r("好き", "すき", "喜欢"), p("ですか。")),
        meaning: "陈同学喜欢音乐吗？",
        keywords: [{ term: "好き", reading: "すき", meaning: "喜欢" }],
      },
      {
        speaker: "陳",
        japanese: jp(p("はい、とても"), r("好き", "すき", "喜欢"), p("です。でも、"), r("歌", "うた", "歌"), p("が"), r("下手", "へた", "不擅长"), p("です。")),
        meaning: "喜欢，非常喜欢。但是我不擅长唱歌。",
        keywords: [{ term: "下手", reading: "へた", meaning: "不擅长" }],
      },
      {
        speaker: "美咲",
        japanese: jp(p("そうですか。わたしは"), r("絵", "え", "画"), p("が"), r("好き", "すき", "喜欢"), p("です。")),
        meaning: "这样啊。我喜欢画画。",
        keywords: [{ term: "絵", reading: "え", meaning: "画" }],
      },
      {
        speaker: "陳",
        japanese: jp(r("美咲", "みさき", "美咲"), p("さんは"), r("絵", "え", "画"), p("が"), r("上手", "じょうず", "擅长"), p("ですね。")),
        meaning: "美咲很会画画呢。",
        keywords: [{ term: "上手", reading: "じょうず", meaning: "擅长" }],
      },
      {
        speaker: "美咲",
        japanese: jp(p("ありがとうございます。もっと"), r("練習", "れんしゅう", "练习"), p("します。")),
        meaning: "谢谢。我会多练习。",
        keywords: [{ term: "練習", reading: "れんしゅう", meaning: "练习" }],
      },
    ],
  },
  exercises: [
    {
      id: "u8-e1",
      type: "multiple-choice",
      prompt: jp(r("音楽", "おんがく", "音乐"), p(" ___ "), r("好き", "すき", "喜欢"), p("です。应填哪个助词？")),
      options: ["が", "を", "で", "に"],
      correctAnswer: "が",
      explanation: jp(r("好き", "すき", "喜欢"), p("的对象用「が」标记。")),
    },
    {
      id: "u8-e2",
      type: "fill-blank",
      prompt: jp(r("料理", "りょうり", "料理"), p("が ____ です。（喜欢）")),
      correctAnswer: "好き",
      acceptedAnswers: ["すき"],
      explanation: jp(r("好き", "すき", "喜欢"), p("表示喜欢。")),
    },
    {
      id: "u8-e3",
      type: "order-sentence",
      prompt: jp(p("排列成“山田很会做饭”。")),
      parts: [r("山田", "やまだ", "山田"), p("さんは"), r("料理", "りょうり", "料理"), p("が"), r("上手", "じょうず", "擅长"), p("です")],
      correctOrder: [r("山田", "やまだ", "山田"), p("さんは"), r("料理", "りょうり", "料理"), p("が"), r("上手", "じょうず", "擅长"), p("です")],
      explanation: jp(r("上手", "じょうず", "擅长"), p("前面的对象用「が」。")),
    },
    {
      id: "u8-e4",
      type: "true-false",
      prompt: jp(p("判断用法。")),
      statement: jp(r("好き", "すき", "喜欢"), p("是な形容词，不是动词。")),
      correctAnswer: true,
      explanation: jp(p("因此常说「"), r("音楽", "おんがく", "音乐"), p("が"), r("好き", "すき", "喜欢"), p("です」。")),
    },
    {
      id: "u8-e5",
      type: "matching",
      prompt: jp(p("匹配词语和中文意思。")),
      pairs: [
        { left: jp(r("好き", "すき", "喜欢")), right: "喜欢" },
        { left: jp(r("嫌い", "きらい", "不喜欢")), right: "不喜欢" },
        { left: jp(r("上手", "じょうず", "擅长")), right: "擅长" },
        { left: jp(r("下手", "へた", "不擅长")), right: "不擅长" },
      ],
      explanation: jp(p("这四个词都常和「が」一起使用。")),
    },
    {
      id: "u8-e6",
      type: "multiple-choice",
      prompt: jp(p("哪一句表示“我不擅长唱歌”？")),
      options: [
        jp(p("わたしは"), r("歌", "うた", "歌"), p("が"), r("下手", "へた", "不擅长"), p("です。")),
        jp(p("わたしは"), r("歌", "うた", "歌"), p("を"), r("好き", "すき", "喜欢"), p("です。")),
        jp(p("わたしは"), r("歌", "うた", "歌"), p("で"), r("上手", "じょうず", "擅长"), p("です。")),
        jp(p("わたしは"), r("歌", "うた", "歌"), p("に"), r("嫌い", "きらい", "不喜欢"), p("です。")),
      ],
      correctAnswer: jp(p("わたしは"), r("歌", "うた", "歌"), p("が"), r("下手", "へた", "不擅长"), p("です。")),
      explanation: jp(r("下手", "へた", "不擅长"), p("表示不擅长，对象用「が」。")),
    },
    {
      id: "u8-e7",
      type: "fill-blank",
      prompt: jp(r("絵", "え", "画"), p("が ____ です。（擅长）")),
      correctAnswer: "上手",
      acceptedAnswers: ["じょうず"],
      explanation: jp(r("上手", "じょうず", "擅长"), p("表示做得好。")),
    },
    {
      id: "u8-e8",
      type: "true-false",
      prompt: jp(p("判断句意。")),
      statement: jp(r("野菜", "やさい", "蔬菜"), p("が"), r("嫌い", "きらい", "不喜欢"), p("ではありません。表示“并不讨厌蔬菜”。")),
      correctAnswer: true,
      explanation: jp(r("嫌い", "きらい", "不喜欢"), p("ではありません是否定表达。")),
    },
    {
      id: "u8-e9",
      type: "order-sentence",
      prompt: jp(p("排列成“喜欢音乐”。")),
      parts: [r("音楽", "おんがく", "音乐"), r("好き", "すき", "喜欢"), p("が"), p("です")],
      correctOrder: [r("音楽", "おんがく", "音乐"), p("が"), r("好き", "すき", "喜欢"), p("です")],
      explanation: jp(r("好き", "すき", "喜欢"), p("的对象用「が」。")),
    },
    {
      id: "u8-e10",
      type: "multiple-choice",
      prompt: jp(p("哪个词表示“不擅长”？")),
      options: [jp(r("下手", "へた", "不擅长")), jp(r("上手", "じょうず", "擅长")), jp(r("好き", "すき", "喜欢")), jp(r("嫌い", "きらい", "不喜欢"))],
      correctAnswer: jp(r("下手", "へた", "不擅长")),
      explanation: jp(r("下手", "へた", "不擅长"), p("表示做得不好或不擅长。")),
    },
  ],
};
