import type { Lesson } from "../types";

export const unit0: Lesson = {
  id: "unit-0",
  unit: 0,
  title: "假名与日语发音基础",
  subtitle: "从声音开始，认识日语的节奏",
  description:
    "认识平假名与片假名的用途，建立清晰的拍感，并用简单寒暄开始第一次日语交流。",
  duration: "约 35 分钟",
  accent: "#d66a4a",
  goals: [
    "区分平假名与片假名的常见用途",
    "理解日语以拍为基本节奏单位",
    "读出基础元音与常见寒暄",
  ],
  vocabulary: [
    {
      id: "u0-w1",
      japanese: "おはよう",
      kana: "おはよう",
      meaning: "早上好",
      partOfSpeech: "寒暄语",
      example: "おはよう、今日は早いですね。",
      exampleMeaning: "早上好，今天来得很早呢。",
    },
    {
      id: "u0-w2",
      japanese: "こんにちは",
      kana: "こんにちは",
      meaning: "你好；午安",
      partOfSpeech: "寒暄语",
      example: "こんにちは、山田さん。",
      exampleMeaning: "你好，山田先生。",
    },
    {
      id: "u0-w3",
      japanese: "こんばんは",
      kana: "こんばんは",
      meaning: "晚上好",
      partOfSpeech: "寒暄语",
      example: "こんばんは。今日は涼しいですね。",
      exampleMeaning: "晚上好。今天很凉快呢。",
    },
    {
      id: "u0-w4",
      japanese: "ありがとう",
      kana: "ありがとう",
      meaning: "谢谢",
      partOfSpeech: "寒暄语",
      example: "手伝ってくれて、ありがとう。",
      exampleMeaning: "谢谢你帮忙。",
    },
    {
      id: "u0-w5",
      japanese: "すみません",
      kana: "すみません",
      meaning: "不好意思；对不起；劳驾",
      partOfSpeech: "表达",
      example: "すみません、駅はどこですか。",
      exampleMeaning: "劳驾，请问车站在哪里？",
    },
    {
      id: "u0-w6",
      japanese: "はい",
      kana: "はい",
      meaning: "是；好的",
      partOfSpeech: "应答",
      example: "はい、わかりました。",
      exampleMeaning: "好的，我明白了。",
    },
    {
      id: "u0-w7",
      japanese: "いいえ",
      kana: "いいえ",
      meaning: "不；不是",
      partOfSpeech: "应答",
      example: "いいえ、違います。",
      exampleMeaning: "不，不是那样。",
    },
    {
      id: "u0-w8",
      japanese: "また",
      kana: "また",
      meaning: "再；又",
      partOfSpeech: "副词",
      example: "では、また明日。",
      exampleMeaning: "那么，明天见。",
    },
    {
      id: "u0-w9",
      japanese: "名前",
      kana: "なまえ",
      meaning: "名字",
      partOfSpeech: "名词",
      example: "名前をゆっくり言います。",
      exampleMeaning: "慢慢地说出名字。",
    },
    {
      id: "u0-w10",
      japanese: "日本語",
      kana: "にほんご",
      meaning: "日语",
      partOfSpeech: "名词",
      example: "日本語の音を聞きます。",
      exampleMeaning: "听日语的声音。",
    },
  ],
  grammar: [
    {
      id: "u0-g1",
      title: "平假名与片假名",
      structure: "ひらがな / カタカナ",
      explanation:
        "平假名常用于日语固有词和语法成分；片假名常用于外来语、拟声词和需要强调的词。",
      usage:
        "两套假名表示的是同一组基本音。例如「あ」和「ア」都读作 a。",
      examples: [
        { japanese: "さくら", meaning: "樱花（平假名）" },
        { japanese: "コーヒー", meaning: "咖啡（片假名外来语）" },
      ],
    },
    {
      id: "u0-g2",
      title: "按“拍”读音",
      structure: "に・ほ・ん・ご = 4 拍",
      explanation:
        "日语节奏通常按拍计算。一个普通假名大多占一拍，拨音「ん」、促音「っ」和长音也各占一拍。",
      usage:
        "练习时保持每拍长度接近，不要把熟悉的汉字词一口气带过。",
      examples: [
        { japanese: "お・は・よ・う", meaning: "おはよう，共 4 拍" },
        { japanese: "きっ・て", meaning: "切手（邮票），共 3 拍" },
        { japanese: "コー・ヒー", meaning: "咖啡，共 4 拍" },
      ],
    },
    {
      id: "u0-g3",
      title: "寒暄中的礼貌感",
      structure: "ありがとう → ありがとうございます",
      explanation:
        "许多寒暄有较随意和较礼貌的形式。对不熟悉的人，使用完整礼貌形式更稳妥。",
      usage:
        "本单元先熟悉短形式；在正式场合可使用「ありがとうございます」和「おはようございます」。",
      examples: [
        { japanese: "おはようございます。", meaning: "早上好。（礼貌）" },
        { japanese: "ありがとうございます。", meaning: "非常感谢。（礼貌）" },
      ],
    },
  ],
  examples: [
    { japanese: "あ・い・う・え・お", meaning: "日语的五个基础元音。" },
    { japanese: "こんにちは。", meaning: "你好。" },
    { japanese: "すみません。", meaning: "不好意思 / 劳驾。" },
    { japanese: "ありがとうございます。", meaning: "非常感谢。" },
    { japanese: "では、また。", meaning: "那么，再见。" },
  ],
  reading: {
    title: "教室门口",
    intro: "第一次走进日语体验课，两位学习者在门口简单打招呼。",
    lines: [
      {
        speaker: "林",
        japanese: "こんにちは。",
        meaning: "你好。",
        keywords: [{ term: "こんにちは", reading: "こんにちは", meaning: "你好；午安" }],
      },
      {
        speaker: "森",
        japanese: "こんにちは。日本語のクラスですか。",
        meaning: "你好。是日语课吗？",
        keywords: [
          { term: "日本語", reading: "にほんご", meaning: "日语" },
          { term: "クラス", reading: "くらす", meaning: "班级；课程" },
        ],
      },
      {
        speaker: "林",
        japanese: "はい、そうです。",
        meaning: "是的，没错。",
        keywords: [{ term: "そうです", reading: "そうです", meaning: "是那样；没错" }],
      },
      {
        speaker: "森",
        japanese: "よかった。わたしもです。",
        meaning: "太好了。我也是。",
        keywords: [
          { term: "よかった", reading: "よかった", meaning: "太好了" },
          { term: "わたし", reading: "わたし", meaning: "我" },
        ],
      },
      {
        speaker: "林",
        japanese: "では、いっしょに入りましょう。",
        meaning: "那么，我们一起进去吧。",
        keywords: [
          { term: "いっしょに", reading: "いっしょに", meaning: "一起" },
          { term: "入りましょう", reading: "はいりましょう", meaning: "进去吧" },
        ],
      },
    ],
  },
  exercises: [
    {
      id: "u0-e1",
      type: "multiple-choice",
      prompt: "哪个假名读作「a」？",
      options: ["あ", "い", "う", "え"],
      correctAnswer: "あ",
      explanation: "「あ」是平假名，读作 a；对应的片假名是「ア」。",
    },
    {
      id: "u0-e2",
      type: "matching",
      prompt: "匹配平假名与罗马音。",
      pairs: [
        { left: "か", right: "ka" },
        { left: "し", right: "shi" },
        { left: "つ", right: "tsu" },
        { left: "の", right: "no" },
      ],
      explanation: "注意「し」读 shi，「つ」读 tsu。",
    },
    {
      id: "u0-e3",
      type: "true-false",
      prompt: "判断下面关于假名的说法。",
      statement: "平假名「い」和片假名「イ」表示同一个音。",
      correctAnswer: true,
      explanation: "两者都读作 i，只是字形与常见使用场景不同。",
    },
    {
      id: "u0-e4",
      type: "fill-blank",
      prompt: "白天见面时，可以说「____」。",
      correctAnswer: "こんにちは",
      hint: "こ 开头的五拍寒暄语",
      explanation: "「こんにちは」常用于白天见面时的问候。",
    },
    {
      id: "u0-e5",
      type: "order-sentence",
      prompt: "排列成自然的告别表达。",
      parts: ["また", "では", "明日"],
      correctOrder: ["では", "また", "明日"],
      explanation: "「では、また明日」意为“那么，明天见”。",
    },
    {
      id: "u0-e6",
      type: "multiple-choice",
      prompt: "哪个词通常用片假名书写？",
      options: ["さくら", "コーヒー", "なまえ", "ありがとう"],
      correctAnswer: "コーヒー",
      explanation: "「コーヒー」来自外语 coffee，通常用片假名书写。",
    },
    {
      id: "u0-e7",
      type: "true-false",
      prompt: "判断拍数。",
      statement: "「にほんご」通常按 4 拍来读。",
      correctAnswer: true,
      explanation: "に・ほ・ん・ご，每个部分各占一拍。",
    },
    {
      id: "u0-e8",
      type: "multiple-choice",
      prompt: "想礼貌地表达感谢，最合适的是哪一项？",
      options: ["いいえ", "すみません", "ありがとうございます", "こんばんは"],
      correctAnswer: "ありがとうございます",
      explanation: "「ありがとうございます」是礼貌的感谢表达。",
    },
  ],
};
